- database/insertData.js
Fixes #22.
Missing `template_id` references in the `createApplication` mutations.
Works now. :)
> Add template_id references to insertData

- database/buildSchema/19_b_application_stage_status.sql
Implements #45 (as discussed in [this comment](https://github.com/openmsupply/application-manager-server/issues/36#issuecomment-700384134) in #36).
Note: have added new .sql file, but numbered it `19_b)_...` -- I think it's best not to re-number other files while we're actively working on them on multiple branches. Let's do all re-numbering as a single issue once schema is fairly stable.
To test: re-run `yarn database_init` script. In PostGraphile GUI, the `stage`, `stage_number` and `status` fields should be available on the `applications` table.
The query:
```
query GetApps {
applications {
nodes {
stageNumber
stage
name
status
}
}
}
```
should yield:
```
{
"data": {
"applications": {
"nodes": [
{
"stageNumber": 1,
"stage": "Screening",
"name": "User Registration: Nicole Madruga", …
```
> #45 Computed columns to application table

- database/insertData.js
- src/components/postgresConnect.ts
- src/server.test.ts
- src/server.ts
Fixes #56
Endpoint is provided at `/check-unique`.
Query parameters are:
- `type`: available options: `username`, `email`, `organisation`
- `value`: the value being checked for uniqueness
Example request URL: `/check-unique/type=email&value=carl@sussol.net`
Check is case-insensitive, so `carlsmith` will return Not Unique if `CarlSmith` is in the database.
Returns a boolean.
I created a unit test suite. Run: `yarn test src/server.test.ts`
And please try out your own queries with Postman.
Also: added one organisation to database in `insertData.js`
> #56 Endpoint to check for unique values

- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
Very small change -- just return all literal strings as-is.
Previously, it was assuming a string was an attempted JSON string, so would throw an error if Invalid JSON. Now it just returns the string. Only down-side is that genuinely invalid JSON strings will not throw an error but return the string. But a worthwhile trade-off to be able to simplify queries like this, for example:
```
{
operator: "CONCAT",
children: [ "Carl", " ", "Smith" ]
}
```
> #74 expression evaluator input handling

- src/components/postgresConnect.ts
- src/components/triggersAndActions.ts
- src/types.ts
Very quick fix, but important -- noticed when I was talking about Actions with @andreievg .
The `record_id` field in the trigger payload had been mis-named as `template_id`. It's not template id, it's the id of record from whatever table it came from -- could be application, review, etc.
> Fix mistake with record_id being labelled template_id in trigger payload

- utils/postgraphile_launch.sh
Just a simple change to the command line (remove specific user) so it'll use the default (postgres) user.
I haven't added any delay before the `insertData.js` script runs, and it seems to work with no problems (with changing table name, say), so should be good there. See if any problems arise for anyone else.
> #39 Postgraphile --watch flag fix

- database/buildSchema/14_template_element.sql
- database/buildSchema/20_application_response.sql
- database/insertData.js
- documentation/Elements-Questions.md
- src/generated/graphql.ts
Changes to handle validation in front end. Please review both PRs together.
Front-end issue: https://github.com/openmsupply/application-manager-web-app/pull/125
- Added `is_valid` field to application_responses table
- Removed `validation` and `validation_message` fields and moved them to template_element parameters (as per @andreievg 's suggestion)
- Updated UserRego template queries to demonstrate validation criteria
> #71F Validation improvements

- database/buildSchema/07_template.sql
- database/insertData.js
- src/generated/graphql.ts
PR to be merge along [Front-end#85](https://github.com/openmsupply/application-manager-web-app/issues/81) issue - in a PR soon!
Added new `is_linear` field on the Template entity.
Use the `isLinear` to set one application as linear and the other as non-linear for testing.
Also have added a few elements with `isRequired` equals false for testing purposes.
> #81F - Add new field is_linear in the Template

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/expression-evaluate-gui/src/App.js
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/types.ts
- src/plugins/action_create_user/src/createUser.test.ts
Bunch of small fixes to expression-evaluator:
- #117 - uses loose equality now (`==`), so `null` equals `undefined`
- #58 - more specific GraphQL errors
- Improvements to GUI expression builder -- selector for "Development" or "Published" version of evaluator
- Better handling of literals in `children` array. So this is now valid:  
`{ operator: "=", children: [ "stringA", "stringA" ] } `
- Few extra tests to check the above
- Updated documentation
> #58 #117 Evaluator fixes

- database/buildSchema/16_application.sql
- database/buildSchema/23_action_queue.sql
- src/components/postgresConnect.ts
- src/components/triggersAndActions.ts
- src/generated/graphql.ts
- src/types.ts
Fixes #119.
The simplest way to force an error situation is to use the current front-end `master` (Commit: f6bdeb9) and submit the UserRego application without filling in any content. (This won't be possible after validation checking is merged to master)
Previously, after an Action failure, an unhandled error was thrown, meaning the `processTrigger` method was aborted and so the Trigger on the application table was being stuck perpetually in "Processing"
The changes here achieve the following:
- Better error handling in back-end: Error messages are written to the action_queue `error_log` and the `processTrigger` method does not abort
- On failure of a sequential action, any subsequent Actions are cancelled, with a "Cancellation" message written to their record in the action_queue.
- The …
> 119 Better error handling for failed Actions

- database/insertData.js
This is conjunction with the login functionality for the front-end. [Issue 115](https://github.com/openmsupply/application-manager-web-app/issues/115) /  [PR](https://github.com/openmsupply/application-manager-web-app/pull/144)
I've created a **new** user registration form that should be come the "proper" user registration form, as opposed to the current `UserRego1` which is for testing more complex functionality. 
The new one is just one page, appropriate validation, and only essential questions. It has code `UserRegistration`, so we can access it at `/applications/new?type=UserRegistration`. This will be the URL that the Login/Register process re-directs to.
We can keep using and amending UserRego1 to test functionality etc.
> #115F New user registration template

- database/insertData.js
Companion to front-end issue 130. (https://github.com/openmsupply/application-manager-web-app/pull/152)
We're only using the one "ResponsesByCode" object in the front-end now, which contains the whole response object (not just "text" field, so some queries needed to be re-written to explicitly refer to `.text` property of questions.
> #130F Use ResponsesFullByCode

- database/buildSchema/07_template.sql
- database/buildSchema/19_application_status_history.sql
- database/buildSchema/21_application_response.sql
- database/buildSchema/22_trigger_queue.sql
- database/buildSchema/24_action_queue.sql
- database/initialise_database.sh
- database/insertData.js
- src/components/postgresConnect.ts
- src/generated/graphql.ts
Implements #135.
_Requires [front-end PR #195](https://github.com/openmsupply/application-manager-web-app/pull/195) to make timestamp fields match, and new template to appear in sidebar._
Added new "ReviewTest" template, with submitted application form into database. Application appears in Application List -- named "Test Review -- Vitamin C"
Also:
- Changed "time_created" in "application_response" to "timestamp", and set a default value of current time, which should also close [front-end issue #172](https://github.com/openmsupply/application-manager-web-app/issues/172).
- Added additional `touch` command to `initialise_database.sh` to force the server to restart after a database init.
> #135 new review test template & application

- database/insertData.js
From [front-end issue #180](https://github.com/openmsupply/application-manager-web-app/issues/180).
No changes required to front-end as it was already implemented in existing plugins. However, I've added a couple of extra questions to the Testing template to demonstrate it.
Go to Page 3 of the "Feature Showcase form" -- the second question only becomes editable after selecting "Other" in the previous question.
> #180F Demonstrate dynamic editability

- database/insertData.js
Addresses #136. Updated `insertData.js` to create a review assignment of the new "Vitamin C" test review application.
Created two new users as well ("Reviewer" and "Assigner") -- unfortunately I accidentally pushed them to master before I realised what branch I was on (Ooops 😖), so you won't see them in this diff, but its line 1641–1668.
Once you've run the database setup script, you can see the details of the review assignment and the questions assigned (all of them) using the following GraphQL query:
```
query ShowReviewAssignment {
reviewAssignment(id: 1) {
application {
name
user {
firstName
lastName
}
}
assigner {
firstName
lastName
}
reviewer {
firstName
lastName
}
reviewQuestionAssignments {
nodes {
templateElement {
title
}
}
totalCount
}
}
}
```
Question: I've currently only …
> #136 Assign application to reviewer

- database/buildSchema/14_template_element.sql
- database/insertData.js
- src/generated/graphql.ts
Back-end counterpart to [front-end issue #194/PR #215](https://github.com/openmsupply/application-manager-web-app/pull/215).
- Moves `validation` and `validationMessage` back to their own fields in `templateElement` instead of being parameters
- Update templates accordingly (`insertData.js`)
> #194F validation updates

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/expression-evaluate-gui/src/App.js
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
- src/modules/expression-evaluator/src/types.ts
Addresses #154 and #145. Was having a quick look last night and both turned out to be super-simple tweaks. Re-factoring the tests, docs and GUI app took 90% of the work!
Once this has been merged I'll re-publish the a new version of the evaluator package and go through and update all the templates and code with the new syntax (#159) -- it's only a very small change, but it's much better. Thanks for the suggestion @andreievg .
So instead of passing in an array of object which need to be referred to by index, you just pass them nested in a single object (e.g. `objects: { user, responses: allResponses } `, and then prefix the property you're fetching with the name of the object (e.g. `responses.Q1.text`). (See docs and tests for more clarity)
- The CONCAT bug (#145) was resolved by just …
> #154 Evaluator named objects and CONCAT bug fix

- database/buildSchema/07_template.sql
- database/insertData.js
- documentation/Database-Schema-Template.md
- src/generated/graphql.ts
To be used as back-end for Front-end issue [182](https://github.com/openmsupply/application-manager-web-app/issues/182).
- Add to table **template** new fields: `start_title`, `start_message` and `submission_message`.
- The submission message has a DEFAULT value, to be used if none is provided.
- Fix a minor problem with section title.
> #182F Add start and submission message to templates

- database/insertData.js
- package.json
- src/components/triggersAndActions.ts
- yarn.lock
Fixes #159. Refactors evaluator queries to accomodate changes made in #161.
**NOTE**: Must run `yarn install` to upgrade evaluator package version. (If you go back to another branch, you'll need to run it again to revert to previous version -- these changes are breaking changes and incompatible between evaluator version 1.2.1 and 1.3.0 (the latest))
Needs to use [front-end PR branch #238](https://github.com/openmsupply/application-manager-web-app/pull/238) in conjunction to test.
Best way to test: Go through the "Feature Showcase" template and check all the visibility/dynamic parameters/validation works as expected when filling in application, and check all Actions run as expected when submitting.
> #159 Refactor for evaluator package update

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
- src/modules/expression-evaluator/src/types.ts
Implements #158.
Did this at the start of the break. Now that @nmadruga has made progress on the start/submission pages, this will probably be useful sooner rather than later (as it'll be a lot easier than multiple CONCATs).
Can see implementation by reading and running test suite.
One thing I didn't (yet) implement is escaping when literal `(%1)` values are required in a string. Probably not a priority as it's very unusual to have a percent character before a number (unless writing documentation for a modulus operator, perhaps), so can do it later if required.
Once approved, will update package and make new PRs to upgrade the module in front and back-ends.
> #158 Evaluator -- string substitution operator

- database/insertData.js
- package.json
- src/modules/expression-evaluator/expression-evaluate-gui/package.json
- src/modules/expression-evaluator/package.json
- yarn.lock
Implement #176. 
Requires [front-end PR #263](https://github.com/openmsupply/application-manager-web-app/pull/263) to see it in use.
Have re-written several of the CONCAT expressions in the FeatureShowcase template to use `stringSubstitution` instead.
(Don't forget to `yarn install` to update package)
> #176 Update evaluator version and implement stringSubstitution

- database/insertData/01_template_A_featureShowcase.js
- database/insertData/01_template_B_companyRegistration.js
I think this is all there is to this one -- the Action already existed, so just added it to two templates that should have it.
Edit: Original issue is [front-end #204,](https://github.com/openmsupply/application-manager-web-app/issues/204) but this is purely a back-end change.
> #204 Add ON_REVIEW_CREATE action to two templates

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
- src/modules/expression-evaluator/src/types.ts
Very small improvement, so I just squeezed this in. Implements #190 which adds a Conditional `?` operator to evaluator. Works exactly like the javascript ternary (`?`) operator.
The actual implementation was two lines of code. Docs and tests slightly more :) 
`yarn test ./src/modules/expression-evaluator/src/evaluateExpression.test.ts` to run evaluator test suite. (On newly initialised database)
> #190 Evaluator -- Conditional operator

- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
Very quick fix. 
Annoying how in javascript an empty string evaluates to `false` -- that's caught me out many times now. Anyway, that's all it was. 
Added additional test to catch this.
> #201 Evaluator -- stringSubstitution bug

- database/insertData/00A_permission_policies.js
- database/insertData/00B_permission_names.js
- database/insertData/01_template_A_featureShowcase.js
- database/insertData/01_template_B_companyRegistration.js
- database/insertData/01_template_C_userRegistration.js
- database/insertData/01_template_D_basicReviewTesting.js
- database/insertData/02_users.js
Had to refactor quite a bit to get this to work -- since most of the permissions were being created as part of the `createUser` section, they weren't available to add to templates that were inserted earlier.
So I've moved all policy creation and permissionName creation to their own files right at the beginning and the createUser mutations just link to existing permission names.
Added a new permission name "reviewReviewTest" with basicReview policy, linked to ReviewTest template and applies to all review stages and levels.
(Currently the new files are numbered 00A and 00B so I didn't have to change the names of other files. We'll renumber correctly at some point)
> #188 Review levels in ReviewTest template

- database/buildSchema/27_review.sql
- database/buildSchema/31_review_status_history.sql
- src/generated/graphql.ts
Small fix, noticed by @nmadruga in the front-end wondering why the GraphQL type for the `status` field on the review table (string) was different to the `status` field on review_status_history.
Turns out the function to generate the computed column on the review table was casting it to VARCHAR. This doesn't seem necessary, so have changed it to use the `review_status` enum type like the original field.
(Also, fixed another tiny typo while I was there)
> Fix -- change type of review_status computed column

- database/insertData/03_template_A_featureShowcase.js
Tiny tweak to Feature Showcase template to add "search" parameter to one element, as implemented in front-end [PR#326](https://github.com/openmsupply/application-manager-web-app/pull/326).
> Add search attribute to Feature showcase

- database/buildSchema/27_review.sql
- database/buildSchema/31_review_status_history.sql
- src/generated/graphql.ts
To be used combined with Front-end branch [PR#411](https://github.com/openmsupply/application-manager-web-app/pull/411)
> #378F Review_status_history to expose the time_created of status in review table

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
Small improvement so that unresolved objects return a fallback value rather than throwing an error. Default fallback is "Can't resolve object", but can be useful to set to `null` in some case if you're not sure that the property will exist (Like for an API call, say).
Since GraphQL and API operators also use the same `extractProperty` method, this will work for those operators too -- I've added a specific fallback for them, mainly for debugging purposesd.
Also updated documentation, and added a couple of additional tests.
Bear in mind that whatever is returned by the node will be passed up back up the tree, so will be treated exactly like it would in normal javascript (e.g. "string" + null => "stringnull"). If you need to test if a property exists before returning something, you can use …
> #240 Evaluator -- handle unresolved objects

- database/insertData/02_permission_names.js
- database/insertData/03_template_D_basicReviewTesting.js
- database/insertData/04_users.js
- src/plugins/action_generate_review_assignment_records/src/generateReviewAssignments.ts
- src/plugins/action_generate_review_assignment_records/src/types.ts
Required for front end: #464-#465-Add-assignments-logic
* Add canSelfAssign to templatePermission.restrictions (and make sure generated reviewAssignments are set to that if it exists)
* Add new permissionName (reviewSelfAssignable - 10500)
* Add template permission and user permissionJoin of permissionName for template testReview, as per below diagram (`under reviewSelfAssignable-10500` branch)
> #464F-#465F-add-self-assignment-option-on-templatePermission

- src/components/permissions/routes.ts
In the process of trying to fix [front-end #494](https://github.com/openmsupply/application-manager-web-app/pull/553) I discovered that the 'user-info' endpoint was only returning a "success" field if it failed, not when `true`, which means the calling function couldn't check for success.
This rectifies that with a very small fix.
> #494F return sucess field in user-info endpoint

- utils/pluginScripts/buildPlugin.js
- utils/pluginScripts/yarnInstallPlugins.js
Getting freezes with postinstall (when plugins are installed), where plugin folder doesn't have package json (i.e. git ignored  node_modules folder exists, but no code). It also seems like cpu usage goes insane (without any log of what's happening, can hear my working overtime)
> Fix nasty bug in postinstall

- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
Fixes #326 
Another quick fix, needed to get proper result for when the query results on `null` as "no results" for the given input.
> #326 Fix to allow result of GraphQL operation to return Null instead of fallback

- database/buildSchema/35_row_level_policy_related.sql
- database/buildSchema/40_graphile_user.sql
- database/insert_data.sh
- database/post_data_insert.sh
- database/turn_on_row_level_security.sql
Came up with a simpler way for insertData to work while PostGraphile is logged in as `graphile_user` (i.e. row-level security enforced)
Basically, I just moved the commands to turn on ROW LEVEL SECURITY out of the main "buildSchema" folder, and now they run separately _after_  insertData has finished.
> #352 Graphile user can insert data

- database/insertData/06_applications_D_reviewTest.js
- database/insertData/07_review_assignments.js
To be run with Front-end PR
[711](https://github.com/openmsupply/application-manager-web-app/pull/736)
This is actually fixing something done previously (to have a Review already submitted with LOQ to Applicant) and the only part that was meant for #711 is adding the ids on reviewResponses and reviewResponseLinkId on the submitted consolidation requesting changes from Reviewer1 (of Application serial: 34567).
- Update previously wrong ids of `applicationResponse` on Review of Application (serial: 23456) with LOQ
- Add correct status of CHANGES_REQUIRED on application and `isVisibleToApplicant` on reviewResponse **Declined** by reviewer to correctly display action to **Update** on Application home page
- Specify ids on `reviewResponses` to be later added in `reviewResponseLinkId` on …
> #711F update assignment review response links and fix application response ids

- database/insertData/core_mutations.js
- src/components/graphQLConnect.ts
Back-end for issue #741
[#741](https://github.com/openmsupply/application-manager-web-app/pull/746)
[#364](https://github.com/openmsupply/application-manager-server/pull/375) 
- Add sequence action ON_REVIEW_START to set `review.status` as LOCKED when `reviewAssignment.isLocked` is true
- Needed to add `reviewAssignment.isLocked` to get returned on `getApplicationData` to show on actions
> #741F create locked review when assignment is locked

- database/insertData/03_template_A_featureShowcase.js
Back-end changes for [front-end PR #755](https://github.com/openmsupply/application-manager-web-app/pull/755)
Changes the Ingredients list demo in FeatureShowcase to more closely reflect the latest Miro designs for Ingredients list, including inline radio buttons and limited-width text inputs.
> #750F #751F Ingredients list updates

- database/buildSchema/14_template_element.sql
- database/insertData/_common/03_template_G_userEdit.js
- documentation/Query-Syntax.md
- package.json
- src/components/triggersAndActions.ts
- src/generated/graphql.ts
- src/modules/expression-evaluator/expression-evaluate-gui/package.json
- src/modules/expression-evaluator/package.json
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
- src/modules/expression-evaluator/src/resolvers/buildObject.test.ts
- src/modules/expression-evaluator/src/resolvers/buildObject.ts
- src/modules/expression-evaluator/src/types.ts
- src/modules/expression-evaluator/tsconfig.json
- src/types.ts
Required for front end PR https://github.com/openmsupply/application-manager-web-app/pull/764: 
note: when this PR is merged we need to push evaluator
* Default value field on element (note this is the full response value, plugin specific)
* Use new defaultValue in userEdit (now requires buildObject evaluation)
* Use EvaluatorNode type for evaluator
* Fix deeply nested query bug, new test added (it won't pass in master)
* New buildObject evaluation (see below notes about evaluator)
* Would need to use new evaluator for this PR to compile, need to repeat the same evaluator related steps as per Testing in front end PR
* See front end testing in PR 'X'
* Use back end branch #761F-testing (`https://github.com/openmsupply/application-manager-server/compare/%23761F-generic-default-value-handling …
> #761F generic default value handling to work for all plugins

- database/buildSchema/02_jwt_config.sql
When restricting by row level policies, I was getting error messages `"message": "invalid input syntax for type boolean: \"\"",` (or for boolean) after changing user, the problem would go away after some delay, but it made policy restricted demo unusable. 
I think if claim is already set, postgraphile would make it an empty string '' when jwt changed. And existing jwt helpers could handle absence of claims but not empty string when casting to bigint and boolean. I think the problem went away after a delay because session (pool?) was reset and no claims were set.
Replication:
`yarn pg_permissions` instead of just `yarn pg`
go to application list with some user, then change to another user that can also see this application list (but through different permission name), you should see an …
> #719F permission policy getters can deal with empty string claims

- docker/database.sh
- docker/entry.sh
- src/components/graphQLConnect.ts
- src/components/permissions/loginHelpers.ts
- src/components/permissions/rowLevelPolicyHelpers.ts
- utils/postgraphile_launch_permissions.sh
There was a problem running graphQL queries with server when permissions are enabled. 
* Starting postgraphile with row level permission with postgres user but with default role 
* Add role as 'postgres' to admin JWT token (loaded into singleton graphQL provider)
* start PG with row policies enabled, try to start/create a review, graphQL query fails to get reviewData and review is locked (due to changeStatus action for locked returning 'can't resolve object')
> Server to use admin jwt for graphQL queries

- database/insertData/_common/02A_permission_names.js
- database/insertData/laos/03_template_license_MMC_MMD.js
- database/insertData/laos/04_template_importPermit(blank).js
- database/insertData/laos/05_template_modernMedicineRego(blank).js
- database/insertData/laos/06_template_medicalDeviceRego(blank).js
- documentation/List-of-Action-plugins.md
- plugins/action_grant_permissions/plugin.json
- plugins/action_grant_permissions/src/grantPermissions.test.ts
- plugins/action_grant_permissions/src/grantPermissions.ts
- src/components/postgresConnect.ts
Fixes #406
- Add `grantPermission` to apply to either `importPermit`, `drugRegoMMD` and `drugRegoMMC` depending on what was selected in the `companyLicense` application.
- Update action `grantPermission` to also take `orgId` (instead of `orgName`) when create a new permission_join between user, organisation and template.
> #406 grant permissions to new templates on approval of company license

- database/insertData/laos/02_template_orgRegistration.js
- database/insertData/laos/03_template_license_MMC_MMD.js
Fixes #409 
Adds a "TextInfo" element to "Company Details" section of Company License application that provides a link to the original Company Registration application.
Made a few small changes to front-end to best reflect this -- see [front-end #795](https://github.com/openmsupply/application-manager-web-app/pull/795)
- Added "Change Status" to "Completed" action to Company Registration template -- was missing.
> #409 Link company license to company registration application

- plugins/action_trim_responses/src/trimResponses.test.ts
- plugins/action_update_review_status/src/updateReviewsStatuses.test.ts
Fixes #433 
While merging PR #431 noticed some tests were broken. In particular the ones that I had made changes (not the reason the tests were broken) and now this has a quick fix for those. The stages `ids` keep changing and I try to fix them, but then tests were failing again and I didn't want to spend more time on this. So, ideally on next fixing of tests we could fix the stages `id` by creating them with fixed ids and using the specific id instead of counting on the order.
> #433 fix trim response and update review statuses tests

- database/insertData/_common/01_permission_policies.js
@nmadruga does this work now as per the use case you've mentioned ? (I've tested, seems to work with my example, although in my example consolidator's response were visible, but not their name, after this change their name appeared, which suggests review became visible)
* restrict review by review assignment application_id (vs reviewer_id)
> #413-adjust-review-visibility-policy

- database/buildSchema/22_application_response.sql
Fixes #430 
Simple Postgres Function and Trigger to automatically update the "time_updated" timestamp whenever the `status`, `value` or `is_valid` is modified, so we don't need to manually patch this value from front-end
Change a value in a response (either manually, or via GraphQL or front-end) -- observe the time_updated field now shows the current time.
> #430 Auto-update timestamp when application_response is updated

- database/buildSchema/13_template_permission.sql
- database/insertData/_helpers/core_mutations.js
- database/insertData/dev/03_template_D_basicReviewTesting.js
- database/insertData/dev/04_users.js
- src/generated/graphql.ts
Fixes #445 
Initial changes as discussed for [EPIC#34](https://github.com/openmsupply/application-manager-web-app/issues/334). So this PR doesn't actually has the full functionality yet, is just adding a new field and allowing the stage to go to next stages when either decision is CONFORM or NON_CONFORM and `is_last_level` reviewer.
❓ Can we guarantee that when the review is submitted on the last level of one given stage the `is_last_level` is set to true? Since this isn't an automatic generated column in `review_assignment` I wasn't sure.
- Added field to template_permission as discussed in Planning
- 2 new users **finalDecision1** and **finalDecision2** already created with new permission_name to make final approval (existing so I didn't change the name, let me know if best to): …
> #445 add canMakeFinalDecision to user and template

- database/insertData/_common/03_template_G_userEdit.js
- database/insertData/_helpers/core_mutations.js
- database/insertData/dev/02_template_userRegistration.js
- database/insertData/dev/03_template_D_basicReviewTesting.js
- database/insertData/laos/02_template_userRegistration.js
- documentation/List-of-Action-plugins.md
- plugins/action_generate_text_string/src/generateTextString.ts
Replaces PR #459, as discussed [here](https://github.com/openmsupply/application-manager-server/pull/459#issuecomment-885342227)
- a core action which generates a very basic serial, but uses the templateCode as the name of its counter
- when new templates are created/duplicated, core actions are copied, so it's easy for template creators to change the generate serial action (in Template Builder) if they want to make a more specific serial generating pattern
- remove default "table" and "field" values from "generateTextStrings", as per suggestion (and add them to templates accordingly)
> #426(2) core action for serial generation

- database/buildSchema/07A_template_category.sql
- database/buildSchema/07B_template.sql
- database/insertData/_common/02D_template_categories.js
- database/insertData/_common/03_template_G_userEdit.js
- src/generated/graphql.ts
Fixes #491 as per agreed solution.
Test with [front-end PR #890](https://github.com/openmsupply/application-manager-web-app/pull/890)
Only extra thing I did was to add an 'icon' field to "template", so each template _can_ have its own icon. Only used in "User" menu for "Edit User details" currently. (If a template icon is called and its not defined, it'll fall back to the category icon)
> #491 Category-specific layout settings

- database/buildSchema/41_database_info.sql
- src/components/exportAndImport/getDatabaseInfo.ts
- src/components/exportAndImport/importFromJson.ts
- src/components/exportAndImport/types.ts
- src/components/postgresConnect.ts
- src/generated/graphql.ts
fixes: #503 
branched from 
enums to be not quoted inside array
* Get type of array through information_schema.element_types 
* add isEnumArray to column type of database info
* remove quotes from stringified gqlValue is isEnumArray
* Take snapshot `yarn ts-node ./database/snapshotCLI.ts take`
* Load snapshot `yarn ts-node ./database/snapshotCLI.ts use`
* Comment out `if (column.isEnumArray) gqlValue = gqlValue.replace(/"/g, '')` and load snapshot :/
> #503 make sure enums inside array are not quoted

- src/components/postgresConnect.ts
Fixes: https://github.com/openmsupply/application-manager-web-app/issues/904
explicit search for table name. this is more evident in docker instance of pg vs local (when creating application schema lookup for modify record takes a bit longer then expected)
> Speed up application creation action sequence

- database/buildSchema/07A_template_category.sql
- src/generated/graphql.ts
Fixes #510 
See front-end ???
Also renamed "MENU" to "LIST", since "MENU" is ambiguous.
So we now have 4 UI locations options:
1. DASHBOARD
2. LIST -- shows in "Application List" menu and links to list page filtered by type
3. USER -- shows in "User" menu (right-button), and links to new application page
4. ADMIN -- shows in "Admin Configurations" menu and links to new application page
> #510 Additional UI Location -- Admin

- src/components/actions/triggersAndActions.ts
No issue sorry, just a quick update I made to demo, so adding it here as well.
Basically, was having a problem with the "condition" expression failing, which was causing the action in the queue to stay in a perpetual "PROCESSING" state, which affected other actions for the same template causing them to fail too.
This fix just specifically handles the case when the condition check fails, and aborts that action (sets it to FAIL rather than PROCESSING) and adds some error info to the error_log
EDIT: Also pushed a quick fix where "outputCumulative" was being returned from scheduled trigger event nested 1 level too deep.
> Actions -- Better handling for condition check fail AND outputCumulative fix from scheduled trigger

- package.json
- src/components/snapshots/useSnapshot.ts
Fixes #541
Two problems fixed:
- files were being imported a level too deep (i.e. `/files/files`), fixed so it now copies `/files/*` rather than `/files` from snapshot folder into (existing) files folder
- post insert script was clearing the files folder. Removed this (which means files folder will start to fill up so will need manual management)
> #541 Snapshots - file import fixes

- docker/Dockerfile
- docker/database.sh
- docker/demo_server/.gitignore
- docker/demo_server/README.md
- docker/demo_server/docker-compose.yml
- docker/demo_server/nginx_config/default
- docker/dockerise.sh
- docker/entry.sh
- docker/postgres_config/pg_hba.conf
- docker/usefullScripts.txt
Fixes: #529 
For full details see screencast from telegram
* New readme file for information about (wasn't sure if it needs to be in the docs)
* demo server folder that can be pushed to demo server (see readme files)
* allow for volumes to work in our current image (by creating a copy of fresh database initialisation and copying during image startup if one doesn't exist, i.e. if it using mounted empty volume)
* create docker compose that exposes grafana and mflow image together (linked their networks) and mounts volumes on local system
* demo server nginx config to live in demo server folder
I've updated demo server with 5002 - mFlow and 5003 - Grafana (reserving 5001 for Grafana of first instance)
Also made a of a 'release' (release candidate)
> #529 grafana and docker compose

- database/insert_data.sh
Quick little fix.
insert_data script assumed `./datasbase/_snapshots` folder already existed, and was copying "basic_snapshot" incorrectly if it wasn't.
Added a `mkdir` to always try and create the "_snapshots" folder first.
> Make snapshots folder if it's not there.

- docker/run.sh
- utils/build_all.sh
Forgot about this in the last PR. The _snapshots folder was only being created as part of snapshot loading, which means that it wasn't yet present in the "build" folder when trying to upload a snapshot (before loading it).
So manually added "mkdir" to create this folder as part of build process.
Tested with full docker build and snapshot upload and import.
> Fix _snapshots folder missing from build

- database/snapshotOptions/templateExport.json
- src/components/exportAndImport/importFromJson.ts
- src/components/exportAndImport/types.ts
- src/components/snapshots/useSnapshot.ts
Fixes: #549 
* Changed tablesToUpdateOnInsertFail import/export option to skipTableOnInsertFail (made it backwards compatible with existing snapshots)
* Instead of trying to update on conflict, just query for that record (need id from that record to make sure we insert related record correctly
I've tested a few scenarios, import doesn't show any errors, and seems logically correct, would be good to give it another test spin, to make sure correct filter joins and template permission are associated with corresponding filter and permission names, for those that conflict
> #549 Skip record with conflicting unique fields values in template import

- src/components/exportAndImport/importFromJson.ts
- src/components/snapshots/takeSnapshot.ts
- src/components/snapshots/useSnapshot.ts
Partial fix to #506
Make sure that only files that are linked to file records in import and export are imported and exported (and base files, in root files directory, so that base snapshot also cary over thumbnails)
* Helper for getting base files name
* Pass file records from import and export to respective copy files methods
* Iterate over each file path (form file records and base files) and copy over to snapshot or files dir (try catch it all to make sure export and import still succeeds)
tested with a few scenarios (new snapshots, snapshots with carbone templates), seems to work, and doesn't remove any existing files
> #506 files to export and import based on file table

- database/basic_snapshot/options.json
- database/snapshotOptions/applicationData.json
- database/snapshotOptions/default.json
- database/snapshotOptions/exampleSingleTemplateExport.json
- database/snapshotOptions/templateExport.json
- src/components/exportAndImport/types.ts
- src/components/snapshots/useSnapshot.ts
Fixes #553  
Added the option "resetFiles", and added it to existing "snapshotOptions" files:
- for full system snapshots ("default"), files folder is cleared on import
- for templates, individual templates, application data, files folder is NOT cleared on import
For existing snapshots (that don't have this parameter in their options file), they WON'T clear files (i.e. default: false)
We should add this option to current demo snapshot.
(Fixed a spelling error in "initialiseDatabase" function name as well)
> #553 Snapshots -- clear files option

- database/buildSchema/30_review_question_assignment.sql
- database/buildSchema/34_review_status_history.sql
- database/buildSchema/39_assigner_action_list.sql
- database/buildSchema/41_application_list_view.sql
- src/components/databaseConnect.ts
- src/components/postgresConnect.ts
- src/generated/graphql.ts
- Front-end PR https://github.com/openmsupply/application-manager-web-app/pull/943
- Add new AssignerAction ASSIGN_LOCKED when all assignable question of an application in stage and level are submitted
- Create new SQL FUNCTION `submitted_assigned_questions_count` to get total questions assigned and submitted
- This is only checking if the current status is submitted TODO> Check ideally should be working for any review submitted at-some-time in review-status-history
- Rename function `template_questions_count ` to `assignable_questions_count `, simplify and also check that there is an application_response associated to be considered as "assignable".
> #926F fix not allow re-assign after completed

- database/basic_snapshot/options.json
- database/basic_snapshot/snapshot.json
- database/buildSchema/44_outcome_display.sql
- docker/demo_server/docker-compose.yml
- src/components/databaseConnect.ts
- src/components/graphQLConnect.ts
- src/components/outcomes/gqlDynamicQueries.ts
- src/components/outcomes/helpers.ts
- src/components/outcomes/index.ts
- src/components/outcomes/postGresToJSDataTypes.ts
- src/components/outcomes/routes.ts
- src/components/outcomes/types.ts
- src/components/postgresConnect.ts
- src/components/utilityFunctions.ts
- src/generated/graphql.ts
- src/server.ts
- tsconfig.json
Fixes #564 #565 #566
Implements API for Outcomes as per spec details in #556 
Note: **Don't** use this with front-end yet, it won't work. This is just the API, so can only interact with endpoints.
(**Update:** there is now a [front-end PR](https://github.com/openmsupply/application-manager-web-app/pull/983), but suggest you still review this as stand-alone using the Postman collection)
Here is a Postman collection to demonstrate and test: 
[Outcomes.postman_collection.json.zip](https://github.com/openmsupply/application-manager-server/files/7150952/Outcomes.postman_collection.json.zip)
Please use the snapshot "outcomes_demo". I have put in the "dev/snapshots" folder in the templates repo on a new branch called `#outcomes-demo`
The changes are summarised in detail in the [original …
> #564 #565 #566 Outcomes API

- src/components/snapshots/takeSnapshot.ts
- src/components/snapshots/useSnapshot.ts
- src/generated/graphql.ts
Fix #575 
Adds an extra line in both import and export to also add the list of thumbnail paths into the files to copy array
Note: Slightly sub-optimal, as it will copy the "generic" icons many times, but it's probably fine?
> #575 Snapshot thumbnail export/import fix

- plugins/action_send_notification/src/sendNotification.ts
Fix #579 
Added two additional protections:
- Checks for email address at start of action, returns FAIL if not present
- The asynchrounous "sendEmail" function has "catch" block, which will set log any email failure error, and NOT crash the server (for example, if you pass an illegal email address, or a mail server problem)
Easiest way to test is use the /run-action endpoint
This should work okay:
```
{
"actionCode": "sendNotification",
"applicationId": 2,
"parameters": {
"email": "<put a proper email address here>",
"subject": "Test email",
"message": "Hello!"
}
}
```
This should cause a failed action (with Fail response):
```
{
"actionCode": "sendNotification",
"applicationId": 2,
"parameters": {
"subject": "Test email",
"message": "Hello!"
}
}
```
And this will show as a "SUCCESS" …
> #579 Better error handling for Email failure

- database/buildSchema/07_template.sql
- database/buildSchema/20_application_stage_history.sql
Fixes #611 
Turns out this was due to the `public.set_template_to_draft` function in `template.sql` being a bit over-eager. Was supposed to make duplicated templates as DRAFT, but didn't really consider re-importing them. Have just added another condition that means it will only do this if there are no other versions with 'AVAILABLE' status.
**Additional:**
I've also added another function in here that will automatically set other "AVAILABLE" version status to "DISABLED" when you enable another version. This is consistent with what we do with "is_current" in stage/status history, and when "Outcome" is changed from "PENDING", etc., so it makes sense to enforce this at the database level. This means the front-end will be able to set a template to "AVAILABLE" without having to go and disable …
> #611 Fix for templates going to DRAFT on snapshot load

- database/insert_data.sh
- database/updateRowPolicies.ts
- src/generated/graphql.ts
This will be needed before we can run the docker script again, as the "database_init" script is currently never finishing.
Turns out that importing the `getAdminJWT` function from another module was causing other methods in that module and it's dependents (which is basically the entire app I think), were executing and then the persistent ones (i.e. the scheduler) were never finishing. 
This fix moves that method and its dependents in the updateRowPolicies directly, so the whole database init process can remain isolated from the main app.
> Fix for database_init script not finishing

- tsconfig.json
I've excluded the whole `/modules` folder from typescript compilation (in tsconfig) as nothing in there is required for the app to run (it's pulled from packages).
This prevents the missing "testSecrets" error.
> Fix for build script

- src/components/outcomes/helpers.ts
Fix #622 
For background, the filter `{ id: { isNull: false } }` is just a dummy filter that is required, or else GraphQL throws an error for "empty filter object".
Previously the logic looked for `null` in row restrictions and puts this dummy filter in if so. Now it also checks for empty object `{}` too (which is the default value for the row_restrictions field)
> #622 Handle either type of empty row restriction (null or {})

- database/buildSchema/13_permission_name.sql
- database/buildSchema/15_template_permission.sql
- database/core_templates/snapshot.json
- documentation/API.md
- src/components/databaseConnect.ts
- src/components/graphQLConnect.ts
- src/components/permissions/index.js
- src/components/permissions/loginHelpers.ts
- src/components/permissions/routes.ts
- src/components/postgresConnect.ts
- src/generated/graphql.ts
- src/server.ts
Fixes #626 and fixes #625
- Add **description** and **isSystemOrgPermission** to permissionName table
- New endpoint `user-permissions` to list all available, granted and list of permissionNames to display for a user on an organisation. If no organisation is given will list granted permissions as the ones with organisation_id = NULL
- More explanation on the issue and API.md
https://www.getpostman.com/collections/3eea5968759aa5a7347d
* Tested running latest `demo_laos` branch: **#template-for-server-PR-626**
> #626 new endpoint user permissions

- documentation/List-of-Action-plugins.md
- plugins/action_grant_permissions/src/grantPermissions.ts
- plugins/action_revoke_permissions/src/databaseMethods.ts
- plugins/action_revoke_permissions/src/revokePermissions.ts
Use front-end PR: https://github.com/openmsupply/application-manager-web-app/pull/1059
- Add type cast to make sure correct functions are called
- Update revokePermisison for user and org to be deleted (permission_join only) to keep this simple  
Using latest **demo_angola** snapshot called: demo_angola_2021_11_25 with the template grantUserPermissions updated 
Question: Do I add something on docs about that change on the revokePermisison action? Probably should right?
> #1046F fix grant revoke permission actions

- src/components/databaseConnect.ts
- src/components/permissions/loginHelpers.ts
- src/components/postgresConnect.ts
I think this is mostly what's required for this to work. 
When fetching template permissions that go into the "userInfo" object and associated JWT, it will also fetch permissions that are associated with just the organisation and have `null` in the "user_id" field (of permission_join).
Test it by manually changing one of the entries in `permission_join` to have `null` in the user_id, and notice that it should allow access for any user belonging to that org. Should work for applicants AND reviewers (not that we'd use if for reviewers much).
> Org-only permissions

- utils/postgraphile_launch_permissions.sh
Just realised this was still in here, whereas the `postgraphile_launch.sh` file doesn't. Changed for consistency.
> Remove NPX from postgraphile launch

- plugins/action_generate_review_assignment_records/src/generateReviewAssignments.ts
Okay, this was something stupid I did the other day at the last minute. Used a Fallback (`??`) when I meant to use a ternary operator. 🙄
Fortunately it's easily fixed. We'll need to get this into a new build ASAP so Jess can continue working with it for her demo.
> generateReviewAssignments quick fix

- database/core_templates/snapshot.json
- database/insert_data.sh
- docker/Dockerfile
- docker/database.sh
- docker/dockerise.sh
- docker/run.sh
- documentation/Demo-Server-Guide.md
- package.json
- src/generated/graphql.ts
Started out by just changing the repo where the LibreOffice package comes from in Dockerfile, and ending up making quite a few changes to massively simplify the build process locally (no more manually editing shell scripts!!)
Now you can start a build (and automatically push it to docker hub) just by running the command:  
`yarn dockerise <tag-name> push` (the `push` is optional)
- **Dockerfile** script:
- Changed the LibreOffice repo to the default Ubuntu source
- Changed the "version" tag (that shows in the front-end footer) to just be the Tag name (way less verbose), so instead of saying "version: front: B-1.0.13 back: B-1.0.13" it'll just say "version: B-1.0.13"
- Removed parameter from "initialise_database.sh" so it loads core_templates (not "dev")
- Manually copy "core_templates" …
> Improvements to Docker scripts

- docker/database.sh
- docker/entry.sh
- src/server.ts
@andreievg  showed me what I needed to do to finally fix this properly and have it work with docker-compose.
Same fix as before, but now it happens in the "entry" script rather than the setting up "database.sh" script, which gets overwritten once the docker-compose volume is attached.
Testing and working with docker-compose (with fresh database reset) on instance 50006.
> Finally! (?) fix missing FDA logo with fresh Docker-compose instance

- src/components/postgresConnect.ts
Based on chat with @jagoje on Telegram:
I realised that it wouldn't work with org-only permissions without a small tweak to the `getUserOrgPermissionNames` query to also consider `userId IS NULL` permission joins.
> Outcomes -- allow org-only permissions

- documentation/API.md
- src/components/permissions/loginHelpers.ts
- src/components/permissions/routes.ts
- src/components/postgresConnect.ts
Fix #664 
A bit of a subtle change here, but makes a big difference in how the "grantPermissions" template works.
- Firstly, the `OR "isUserCategory" = true` clause in "getTemplatePermissions" was giving false data when used in this endpoint (although it was doing the expected thing when used in the /login endpoints). It was always returning that whatever permission name is associated with the "User" category is granted to the user/org even when it wasn't. I've added an additional parameter to "getTemplatePermissions" which allows turning this on or off -- it's only useful in the login context.
- Better handling of null/undefined values for username or orgId. These parameters can either be omitted, or accept `orgId=null` / `orgId=0` and `username=""` as the same thing. Useful for the …
> #664 Fix user permissions endpoint

- documentation/List-of-Action-plugins.md
- plugins/action_modify_record/src/modifyRecord.ts
Fix #668
Also solves the issue raised by [front-end #1125](https://github.com/openmsupply/application-manager-web-app/issues/1125) -- we don't need to make changes to that plugin, the problem was that ISO dates weren't being interpreted as postgres "date" types, so I've fixed that here.
Basically, it'll be much easier to fill in "modifyRecord" actions in the template builder now -- instead of painstakingly filling out a dozen (or more!) separate parameters, each with their own evaluator expression to fetch data from form responses, we can now do it all in one with a simple mapping from form responses to data record values. (See docs and original issue for more details)
Easiest way to test is to use the `/run-action` endpoint, with something like this as the body JSON:
```
{
"actionCode": …
```
> #668 modifyRecord improvements & #1125F

- documentation/Query-Syntax.md
- src/modules/expression-evaluator/package.json
- src/modules/expression-evaluator/src/evaluateExpression.test.ts
- src/modules/expression-evaluator/src/evaluateExpression.ts
- src/modules/expression-evaluator/src/evaluateExpressionTestData.ts
Fix #488 (and front-end [#908](https://github.com/openmsupply/application-manager-web-app/issues/908))
Finally got round to adding this. Arrays can now be access via index, and output types can be coerced into other types. Will make certain queries a bit less hassle in templates.
All previous behaviour is preserved, and I've updated the docs to explain a bit more detail.
Have added a few new tests to check the new behaviour. All previous tests still pass.
> #488 #908F Evaluator array access

- documentation/Query-Syntax.md
- src/components/actions/evaluatorFunctions.ts
Adds a simple `getYear` function to "evaluatorFunctions" which can be called from evaluator expressions.
Note, these are only available in the back-end currently. We're not passing any functions into front-end query evaluations.
Also -- realised I hadn't actually documented this operator, so have updated that.
> #692 Evaluator functions -- getYear

- src/components/files/createDefaultFolders.ts
- src/lookup-table/controllers/ImportCsv.controller.ts
- src/lookup-table/controllers/ImportCsvUpdate.controller.ts
This is back-end branch required for front-end [PR #1150](https://github.com/openmsupply/application-manager-web-app/pull/1150)
*Finally* got a fix for that annoying random error when uploading certain files.
Still not sure exactly why it happens, seems to be some kind of bug with Fastify or its file-handling plugin, but it just spits an error on certain files for no apparent reason. Anyway, when I isolated it to that, I remembered that I'd had a similar problem with the file upload endpoint. So all I've done here is change this endpoint to handle files the same way that one does and it seems to work. Basically, we process an iterable of `request.files()` rather than a single `request.file()`.  Don't fully understand what's going on here, but it seems to be working!
Edit: I've put the …
> 1033B Lookup table fixes

- database/buildSchema/15_template_permission.sql
- database/migration/migrateData.ts
Fixes #696 
Required to display the `description` (translated to portuguese) instead of the name on the CreateIntUser template
> #696 add description to user permissions endpoint

- src/components/snapshots/useSnapshot.ts
Fix #730 
I think this should address all potential cases when the default icons are not showing up. When we load a snapshot using the command line `database_init`, etc. the server automatically restarts and `createDefaultDataFolders` gets run. But when loading a snapshot on a running instance using the web UI, this doesn't happen. So I've just added a single call to `createDefaultDataFolders` after loading the snapshot to ensure that the generic thumbnails get recreated no matter what.
> 730 Fix default document icons

- plugins/action_modify_record/src/modifyRecord.ts
Fix #732 
I realise the type detection function didn't actually handle JS `Date` objects themselves, I'd only written matchers for ISO date and time strings. So good to fix this.
You can test it with the Angola product registration template (the "registration date" field), but a quicker test is to load this snapshot from the templates repo: `/dev/snapshots/[TEMP]_732_data_type_fix` 
Trigger the `DEV_TEST` trigger on the application with ID = 97 -- the product table will be created with correct "expiry_date" and "registration_date" fields as `timestamptz` types.
> #732 Fix Date input for modifyRecord

- src/components/permissions/rowLevelPolicyHelpers.ts
closes f/e [#1162](https://github.com/openmsupply/application-manager-web-app/issues/1162)
What was happening ?
When app is used concurrently, jwt claims set as local variable for postgres transaction are not cleared to null, but to empty string, and when row level permission policies access those values coalesce doesn't capture the empty string use case and fails casting empty string to integer. After some time the claims are cleared that's why problem was hard to figure out.
Replicate in dev environment:
* run all with pg_permissions
* have two tabs of app open (either with incognito or with different browsers)
* in one log in as user with org, in the other stay on login page
* refresh the user with org table and try creating user registration, should see integer: "" error
How does this …
> FE 1162 Row level policies to handle empty string for integer jwt claim values

- src/components/data_display/helpers.ts
- src/components/data_display/routes.ts
- src/components/data_display/types.ts
- src/components/utilityFunctions.ts
Fix #761
Data view entries do **NOT** require the prefix in the table name column -- it will automatically be added (and we check for the non-prefix version as well), but if you do add the prefix it should still work.
You'll need to rename the application join table to match then name of the entity table it's linked to (e.g. data_table_product -> data_table_product_application_join) AND update the column name to have the prefix included (i.e. product_id -> data_table_product_id)
> #761 Data views fix

- database/buildSchema/16_template_element.sql
- database/migration/migrateData.ts
Adds extra enum value for is_reviewable_status: `OPTIONAL_IF_NO_RESPONSE`
Required for front-end PR ?? (Coming soon)
@nmadruga The migration code will conflict with your PR, so we'll need to co-ordinate resolving that at some point.
> #1199F Optional reviewability schema update

- src/components/actions/evaluatorFunctions.ts
Couple of date functions which make it easier to get the current time. "modifyRecord" should be able to parse both JSDate and ISO string, but JSDate would be safer, so use that when possible.
> Evaluator functions -- couple of date functions

- src/components/databaseConnect.ts
- src/components/permissions/routes.ts
- src/components/postgresConnect.ts
- src/components/snapshots/useSnapshot.ts
Fix #830 
Use front-end: https://github.com/openmsupply/conforma-web-app/pull/1332
This will be pretty handy for reminding ourselves which snapshot we have loaded on various instances. When loading a snapshot, we save the snapshot name in the "system_info" table, then return this info with prefs. In the front-end it can be displayed in the Footer (to Admin only):
> #830 Return snapshot name to front-end

- database/buildSchema/32_review_response.sql
- database/migration/migrateData.ts
- src/generated/graphql.ts
Fixes #820 
Requires Front-end PR: [1331](https://github.com/openmsupply/conforma-web-app/pull/1331)
- Adds new field to review_response called `is_latest_review_submission` that should be only set to TRUE once the review is submitted and for the reviewed elements in THIS review. So, it shall be listing ALL review_responses on latest review.
- Creates new Trigger and Function to update other review_responses for same `template_element_id` and `review_id` after new review_response gets created (when the user clicks to Re-review application)
Snapshot to use: `dev/snapshots/re-review-showing-correct-LOQ`
After loading it please remember to run `yarn migrate`
Just needs to log in as user `jess` and "Reavaliar" the Review for "[Registo de Medicamento - Medicamento …
> #820 improvement review responses part of latest review submission

- src/components/snapshots/useSnapshot.ts
Fix #827 
Finally worked out what's going on here! Every time I tried to replicate it, I couldn't -- and yet the annoying, nested "localisations" folder kept appearing inside the snapshot folder... *sometimes*.
Turns out, we weren't completely clearing out existing content in the "localisation" and "preferences" in our snapshot script.  And so one of you... 👀 must have had some crap left in your localisation folder from waaay back which was never getting deleted. And so every time _that particular person_ saved a snapshot, this crap came along with it. The reason why I couldn't reproduce it is that my localisations folder was clean...but someone else's wasn't. 🤨
Now that I understand what's going on -- it's a simple fix: just clear out the localisation and preferences folders when we load …
> #827 Fix for stray data in localisation (and prefs) folder

- .postgraphilerc.js
Fix front-end https://github.com/openmsupply/conforma-web-app/issues/1302
Two-pronged fix for this one:
- increase the "bodySizeLimit" for Postgraphile POST request (to '500kb', default is '100kb') (in this PR) ([PG docs ref](https://github.com/openmsupply/conforma-web-app/issues/1302))
- don't submit response values in "application submit" mutations (front-end PR ??)
> #1302B Increase 'bodySizeLimit' for postgraphile

- src/components/actions/processTrigger.ts
Fix #839 
Not sure how/when this changed, but have changed it back to how it was -- when an action fails, other actions in the sequence don't run, and the trigger is marked "ERROR".
> #839 Re-instate action fail behaviour

- src/components/snapshots/triggerTables.ts
Fix #845 
Just removed `template` table from the list of tables which get triggers disabled on snapshot load.
Please let me know if you can think of any others that might cause problems. (I don't think there are any other triggers that are required during snapshot load)
> #845 Fix for template version bug

- src/components/actions/evaluatorFunctions.ts
- src/components/snapshots/triggerTables.ts
- src/components/snapshots/useSnapshot.ts
Fix #849 Part 1:
> 1. change the "disable trigger" script that I altered the other day to _not_ disable when doing a template-only import (and restore "template" to the list of triggerTables)
Part 2 done in front-end [#1344](https://github.com/openmsupply/conforma-web-app/pull/1344)
> #849 (1) Disable triggers only for full database re-init

- src/components/actions/evaluatorFunctions.ts
Added in Conforma-templates issues list since was made for country-specific requirement: 
Fixes https://github.com/openmsupply/conforma-templates/issues/31
Basically added new option on `getFormmatedDate` same as in Front-end (where explained in details) [PR-Front-end](https://github.com/openmsupply/conforma-web-app/pull/1349)
> #31T - Adding new optional locale to getFormattedDate function

- documentation/List-of-Action-plugins.md
- plugins/action_revoke_permissions/src/databaseMethods.ts
- plugins/action_revoke_permissions/src/revokePermissions.ts
Fix #856 
Changes action so that "undefined" (i.e. not provided) will match ALL. `null` will still only match explicit `null` values.
This is so we can revoke ALL permissions related to a company, no matter which user(s) they are linked to.
> #856 revokePermission changes

- docker/entry.sh
When dockerised server is restarted, logs are disappearing. Looks like `tee` command needs to have `-a` for appending rather then overwriting log file. 
/var/log/conforma volume should also be added, this is for log to persist after upgrades (volume should still persist after docker container restarts, unless container is removed)
> Update docker entrypoint to append log on restart

- src/lookup-table/models/LookupTable.model.ts
Fix #886
This was my bad -- when I made improvements to modifyRecord a while back, I changed the "dataTablePrefix" in config.ts and included the underscore in there, but I forgot to remove it from the lookup table code. 🙄
Still, it's one of the smallest PR's you'll ever get to review ;)
> #886 Fix lookup table export

- documentation/List-of-Action-plugins.md
- plugins/action_remove_user_org/src/removeUserOrg.ts
- plugins/types.ts
- src/components/postgresConnect.ts
- src/types.ts
Based in: #874 (I think it was the one used for latest build...)
Fixes https://github.com/openmsupply/conforma-templates/issues/18
- Load [disableOrg-3 template](https://github.com/openmsupply/conforma-server/files/9760354/disableOrg-3.zip) in latest snap shot. Make sure is set as Available.
- Try removing one organisation. (ex: 13) - Log in as `manager` and use the template (Top Menu => Gerência => Desativar Entidade)
- See how it's removed by running this Graphql query **before** and **after**
1. Allow passing `username` and/or `orgName` instead of ides
2. Enforces that some orgId or orgName was passed - it cannot be null
3. When no userId or username is passed (`undefined`) will interpret as remove ALL used connected to org
4. Keeps same logic to remove permissionJoins - for the pair …
> #18 Extend action to remove org join to all users

- database/buildSchema/43_views_functions_triggers.sql
Fix #932 
This also fixes the problem @nmadruga was having loading my snapshot for https://github.com/openmsupply/conforma-web-app/pull/1386!
Turns out that (somehow) the auto-generated values for the "template_code" and "template_version" on the "template_element" table were missing (had `null` values), and also the "unique" constraint for `template_code, code, template_version` was not being re-generated, and this constraint was required as part of the `templateElementByTemplateCodeAndCodeAndTemplateVersion` query the HistoryPanel uses
This change just drops and recreates the generated columns, and ensures the uniqueness constraint is re-added every time.
In order to test -- download `angola_2022_09_27_1616_server` from the Angola SERVER (50000), load it, and go to the review shown in …
> #932 fix crashing on history panel

- src/components/snapshots/takeSnapshot.ts
Quick fix for problem @fergie-nz noted.
Just need to `await` the archiving commands, otherwise the `zipSnapshot` function reports done before it's fully finalised.
> Fix template export zip bug

- database/buildSchema/27_review_assignment.sql
- database/buildSchema/43_views_functions_triggers.sql
Okay, so this fixes the problem, but I'm still somewhat mystified as to why the "review" and "template_element" generated columns need to be recreated like this but other ones don't (like the one in "review_assignment", and "application_status_history") -- they seem to work exactly the same way.
> Fix for missing generated column data

- plugins/action_update_review_assignments_status/src/databaseMethods.ts
- plugins/action_update_review_assignments_status/src/updateReviewAssignmentsStatus.ts
Fixes https://github.com/openmsupply/conforma-templates/issues/70
Try checking using current snapshot loaded on demo instance 50004. Or use the latest on Fiji shared snapshot 
Problem was due to difference on returned (by `getMatchingReviewAssignments` Pg function) of snake_case and camelCase (expected). So now the only properties used are returned and converted to camelCase.
I still noticed that after Unassigning the page doesn't reload - so planning to add this fix to Front-end PR https://github.com/openmsupply/conforma-web-app/pull/1409
> #70T-Fix-trigger-issue-after-unassignment

- docker/demo_server/nginx_config_single/default
Fix #66T
Have already implemented this on Fiji server: https://fiji.conforma.nz
Just changing it here for our default single-instance setup for future installations.
> #66T Remove port requirement from single-instance servers

- database/buildSchema/38_data_view.sql
- database/migration/migrateData.ts
- src/components/data_display/routes.ts
- src/generated/graphql.ts
Back-end tweaks required for front-end issue: https://github.com/openmsupply/conforma-web-app/issues/1412
Adds another column to "data_table" to connect a "data_view" definition to a lookup table.
Also handles the "special" permission names "lookupTables" by inserting data views matching it into the list of "allowed" data views if the auth token contains `isAdmin` (which is what is required for viewing lookup tables, currently)
> #1412B Lookup table Dataview display

- database/buildSchema/43_views_functions_triggers.sql
Back-end branch for front-end PR https://github.com/openmsupply/conforma-web-app/pull/1435
Function was broken, but hadn't noticed as it worked fine with the *first* assignment for each stage/level. But didn't work for other ones. And also, forget to filter by "application_id" in the WHERE clause.
> #1431B assignment validation function fix

- database/buildSchema/43_views_functions_triggers.sql
Based on PR #956 (meant to be included in `feature/final-decision-fixes` branch)
Missing fix to not display Self-assign when there is another reviewer assigned on all available sections...
Check problem described in task list of issue #953
> #953 Fix to only show action SELF_ASSIGN while there are available_sections to be assigned

- plugins/action_generate_document/src/generateDoc.ts
- src/components/exportAndImport/importFromJson.ts
Fix #961 
Requires back-end https://github.com/openmsupply/conforma-web-app/pull/1439
Changes required to preserve association between documents and templates so they get exported and re-imported correctly. See inline comments for more info.
[fileUpload-4.zip](https://github.com/openmsupply/conforma-server/files/10009734/fileUpload-4.zip)
Use this template to test.
- Use it to upload a file, setting the subfolder and associated template.
- Notice that the file record in the database has the template_id correctly linked.
- Export the template from the templates page
- If you unzip it, you'll notice the connected file is included (and hopefully nothing else)
- Load a different snapshot (that doesn't have this template)
- Import the exported template
- The linked file should be copied in and …
> #961 File handling fixes

- database/snapshotOptions/templateExport.json
Fix #967 
Requires front-end https://github.com/openmsupply/conforma-web-app/pull/1443
This is not a complete fix -- there's still cases you can create where this doesn't work properly, but these problems already exist for existing connected elements (e.g. permissionNames), and fixing them would be a whole lot extra. (For example, if you import a template with categories or permissionNames that don't already exist in the system, it'll only create new ones if the "id" *matches* an existing entry -- you'd think the other way round would be the expected behaviour, but 🤷‍♂️. Again, this needs a complete re-write).
However, this will sort out the case we mostly deal with -- exporting a template to import into another (similar) server.
And it doesn't break the linked file import, so that's …
> #967 Template category export/import fix

- plugins/action_modify_record/src/modifyRecord.ts
- src/config.ts
We have some protection so that actions can't write to tables other than "data_table_..." and a few key others (in `config.allowedTableNames`
This included "application" table, which we need access to for updating serials, etc. 
However, what we *don't* want is the schema being changed on these tables. Fergus had a "generateText" action that was adding additional columns to the "application" table, which caused errors due to name conflicts.
We need to completely prevent this, as it's a loophole we've overlooked. This PR just makes an additional list of tables that can be written to, but not have columns added. If you try and run an action that would add a column to these, it'll throw an error.
> Prevent adding columns to application and file tables

- src/components/files/cleanup.ts
- src/server.ts
Quick fix: 
- change order of startup functions, so "createDefaultDataFolders()" runs before "cleanUpFiles()"
- put clean-up script in try/catch block so it will fail gracefully
Either of those on its own would fix the current problem, so we've some extra redundancy :)
> Fix cleanup script when files folder not present yet

- src/components/actions/getApplicationData.ts
- src/components/permissions/loginHelpers.ts
- src/components/postgresConnect.ts
- src/config.ts
Fixes [Front-end PR](https://github.com/openmsupply/conforma-web-app/pull/1448)
- Move preferences about SystemManager permissionName to be in back-end of `defaultSystemManagerPermissionName` (default) or project-specific to be defined in `preference.json`.
- Return User including values of `isAdmin`, `isManager` and `permissionNames` (it doesn't seem to be used, but still)
> #1445B - Moving isAdmin, isManager and permission names to returned User

- src/components/actions/getApplicationData.ts
- src/types.ts
Fixed the problem, but also added stronger Typescript definitions so we don't run in to this again. If we'd had this in place earlier, we wouldn't have been able to make this mistake in the first place. 
In hindsight, we really should have been using an automatic Types generator for PostGres like we have for GraphQL, but alas, we live and learn...
> ApplicationData fix

- src/components/actions/coreActions.ts
- src/components/actions/processTrigger.ts
Fix #975 
Oh my god, I can't believe we didn't do this ages ago -- it's so much easier to keep a handle on these core actions if they're all in one place like this and it was incredibly simple to implement. Works a treat :) 
I haven't actually got all the actions correct yet -- @nmadruga, you and I should sit down together and go through them carefully, but it's so much easier to know we can do it once and it'll be correct everywhere!
Still to do:
> #975(1) Handle core actions

- database/buildSchema/07_template.sql
- database/migration/migrateData.ts
- src/components/actions/coreActions.ts
- src/components/actions/processTrigger.ts
- src/components/databaseConnect.ts
- src/components/postgresConnect.ts
- src/generated/graphql.ts
- src/types.ts
Continuing implementation of #975
Edit from front-end using PR https://github.com/openmsupply/conforma-web-app/pull/1453
Adds "serial_pattern" field to "template" table, which is used by the core action to create the initial application serial.
> 975(2) Core actions serial pattern

- plugins/action_update_review_status/src/updateReviewStatuses.ts
Fixes #985
filter out the current review from list of associated reviews
> Quick fix - remove current review from associated reviews to update

- plugins/action_create_verification/src/createVerification.ts
Fix #984
Explanation of the problem this solves in the issue comment: https://github.com/openmsupply/conforma-server/issues/984#issuecomment-1334701491
One thing to consider -- should we do this for any other nano-ids? The only one I can think of is the file unique id, but I can't think of a case where we'd be putting the id as part of a url in a Markdown/text field. Can you? (If so, I'll make a general method)
> #984 Prevent verification links possibly not being parsed correctly

- database/buildSchema/43_views_functions_triggers.sql
closes: #983
Please see last comment of issue for details.
I've tested this on the snapshot mentioned by @CarlosNZ in the issue, tried a few users and compared application list results, they all seem to match. I think I've spent majority of the time on the assigner actions, but figured out a pretty simple way to check (see comment and `assigned_sections_by_stage_and_level` view).
Carl suggested that I should remove unused methods, I did a search on both front end and back end (on front end camelCase on backend snake_case, I think it's safe to delete them but not 100% sure).
Tested with opening existing snapshot, seem to upgrade correctly
> 983 - Improve application list performance

- documentation/List-of-Action-plugins.md
- plugins/action_send_notification/src/sendNotification.ts
The sendNotification action was defaulting to the applicant userId and email address if these fields weren't specified in the Action, which is not what we want in many situations.
This just removes those defaults. 
If there's any existing templates that are relying on this default, they'll need to be updated -- but I don't think there are, we've been adding explicit to/email parameters hopefully.
> Remove applicant defaults from sendNotification

- package.json
- src/components/actions/coreActions.ts
Fixes https://github.com/openmsupply/conforma-templates/issues/111
There was 2 problems: Actions n. 3 and n. 4 that should have had the same condition were using a slight different condition, so n. 3 (generateDoc) wouldn't run and n. 4 (sendNotification) was trying to send an attached file not created on n. 3
The change on core-actions was required though since the **IncrementStage** was running before all the specific actions were running and would make an inconsistent state, as the action were checking it was a Submitted CONFORM review on Stage 3. But when it was running it should be Stage 2! Now with this change, it will correctly show that when submitting a review of Stage 2, the actions 3 and 4 that should be checking CONFORM on StageNumber = 3 will not run anymore.
This is a …
> #111T Move IncrementStage action to happen AFTER other specific actions run

- src/components/data_display/generateFilterDataFields/databaseMethods.ts
- src/components/data_display/generateFilterDataFields/generateFilterDataFields.ts
Urgent fix for filter data not being generated for new Chemical Import permits (Fiji).
Reason was (and why I hadn't noticed before) is that the "table name" used in "modifyRecord" was "permit_chemical", whereas this method had been expecting camelCase table names (which is what the data view definition is saved as in the "table" column).
So now I've just made it that it'll work for any type of table name specified in modifyRecord. So all of these inputs will work:
- `permitChemical`
- `dataTablePermitChemical`
- `data_table_permit_chemical`
- `permit_chemical`
> Generate Filter Data fix

- src/components/actions/evaluatorFunctions.ts
Required for issue https://github.com/openmsupply/conforma-templates/issues/113
to enable generating an expiry_date prior to creation of product - so it's based on the `statusHistoryDate` of currentStage. And that's the same one which will be used afterwards when creating the product.expiry_date on last stage approval
> Allow entering initialDate to generate an expiry date

- src/components/actions/evaluatorFunctions.ts
Fixes #1004
Required a new evaluator function to remove permissions from the array returned by user-permissions, so not all of the permissions displays in specific templates. Work to be used in configuration of https://github.com/openmsupply/conforma-templates/issues/55
> #1004 Add new filter to remove elements in array

- src/lookup-table/models/LookupTable.model.ts
- src/lookup-table/services/LookupTable.service.ts
- src/lookup-table/utils/dataTypeUtils.ts
- src/lookup-table/utils/index.ts
Fix #997 
Requires front-end https://github.com/openmsupply/conforma-web-app/pull/1471 in order for the UI to work with this.
Tried to be as minimally invasive to the existing code as possible, so this just intercepts the existing imported data and mutates the fieldMap and data rows in-place to conform to inferred data type. The postgres fields will be one of:
- `varchar` (what they all are by default)
- `integer`
- `double precision`
- `boolean`
- `timestamptz`
- `jsonb` (the one we really want for scraped data import)
Test it with the following.
Import this lookup table, and notice the different data types in the created table:
[test_data.csv](https://github.com/openmsupply/conforma-server/files/10424847/test_data.csv)
Then import this one over the top to see the effect of modifying the …
> #997 Lookup table type inference

- database/buildSchema/18_application.sql
- database/migration/migrateData.ts
Fixes #55T
Adding an extra column to `application` table since it cannot be modified using `modifyRecord` due to our own restrictions, we should always add columns in the database when application needs to be altered.
With that in place we can store the generated registration to the application record in a different stage than the one that needs to use the same registration (and add to the product).
> Add column registration on application table

- package.json
- src/components/snapshots/takeSnapshot.ts
Fix #1007 
Turns out this was mostly a front-end problem -- see PR https://github.com/openmsupply/conforma-web-app/pull/1475
However, there was one `await` missing here. I guess it wasn't essential as it wasn't causing any real problems, but it's slightly more thorough.
> #1007 Template export fix

- database/migration/migrateData.ts
- documentation/Data-View-Filters.md
- documentation/Data-View.md
- src/components/data_display/routes.ts
Fix #1026.
Pretty straightforward to implement -- just returns a url query filter string for each data view -- front-end handles the rest.
Front-end: https://github.com/openmsupply/conforma-web-app/pull/1484
> #1026 Default filters for Data Views

- documentation/List-of-Action-plugins.md
- plugins/action_schedule_action/src/databaseMethods.ts
- plugins/action_schedule_action/src/scheduleAction.ts
Fix #1021 
As well as allowing either `date` or `duration` parameters, I've also tightened up the validation of parameters with slightly more informative error message.
To  test, just use the `runAction` endpoint and update the parameters like so:
```
// Duration as number
{
"actionCode": "scheduleAction",
"applicationId": 880, 
"parameters": {
"eventCode": "test",
"duration": 5 // 5 weeks
}
}
// Duration as object
{
"actionCode": "scheduleAction",
"applicationId": 880, 
"parameters": {
"eventCode": "test",
"duration": { "years": 5 } // 5 years
}
}
// Date as ISO string
{
"actionCode": "scheduleAction",
"applicationId": 880, 
"parameters": {
"eventCode": "test",
"duration": "2026-03-01"
}
}
// Date as object
{
"actionCode": "scheduleAction",
"applicationId": 880, 
"parameters": { …
```
> #1021 Scheduled action -- allow specific date input 

- plugins/action_modify_record/src/modifyRecord.ts
Fix #1018 
Just a problem with the ordering of events -- it was doing the `null` check before the full record had been created, which is why it worked in some cases but not others.
Seems good now.
> 1018 Fix for new columns with `null` values

- plugins/action_send_notification/src/sendNotification.ts
- src/components/actions/getApplicationData.ts
- src/components/snapshots/useSnapshot.ts
- src/components/utilityFunctions.ts
- src/config.ts
- src/types.ts
Fix #1016 
Just mutates the config object directly, which affects all "config" references throughout (since they're all using the same original object).
If you want to test, just add a `console.log(config)` somewhere and notice how it changes after loading a different snapshot (assuming its prefs are different), but doesn't change when on `develop`.
> #1016 Reload preferences after snapshot load

- src/components/permissions/loginHelpers.ts
- src/components/permissions/routes.ts
- src/components/permissions/rowLevelPolicyHelpers.ts
This prevents a potential privacy problem as outlined in the [templates repo #137](https://github.com/openmsupply/conforma-templates/issues/137).
The username is now included in the JWT token data. And so we can compare the token username to the user data fetched when loading (based on userID). And if they don't match, we don't allow fetching any user data, and the front-end will be logged out.
**To test**:
- On `develop`, log in as userID 100 (ext1) on PNG snapshot. Then (from another browser), load the Fiji snapshot. Then refresh the original browser. You'll now be logged in as a different person (with ID 100).
- Switch to this branch, then repeat the above procedure. You should be logged out when refreshing.
> #137T Add username authorisation check

- documentation/API.md
- src/components/databaseConnect.ts
- src/components/permissions/loginHelpers.ts
- src/components/permissions/rowLevelPolicyHelpers.ts
- src/components/postgresConnect.ts
- src/lookup-table/routes.ts
- src/server.ts
- src/types.ts
Fix #816 
Requires front-end https://github.com/openmsupply/conforma-web-app/pull/1501
Changes "/lookup-tables" endpoint from being an "admin" route to a normal authenticated route. However, it has an additional check for *either* "admin" or "systemManager" permission.
> #816 Allow manager to access lookup tables

- database/buildSchema/24_action_queue.sql
- database/migration/databaseMethods.ts
- database/migration/migrateData.ts
- package.json
- src/components/actions/getApplicationData.ts
- src/components/actions/processTrigger.ts
- src/components/databaseConnect.ts
- src/components/postgresConnect.ts
- src/types.ts
Fix #1035 and #1036
The migration to add "application_id" column is a bit gnarly, but it's worth it to have this in there -- it also means actions and triggers that no longer have an associated application will automatically get deleted.
**For #1035**:
- Load various snapshots, and check that after loading/migration, the `trigger_queue` and `action_queue` tables have a populated `application_id` field.
- Try doing a few things that cause triggers (start/submit/assign etc) and check that the actions behave as normal and that they get `application_id` stored in the action and trigger queues
**For #1036**:
- Find a submitted application, then remove the applicant from the organisation they applied on behalf of. Then run the `getApplicationData` endpoint -- you should still get the correct …
> #1036 #1035 applicationData fix and additional migration

- documentation/API.md
- documentation/Preferences.md
- src/components/files/createThumbnails.ts
- src/components/permissions/index.ts
- src/components/permissions/routes.ts
- src/components/preferences/index.ts
- src/components/preferences/routes.ts
- src/components/snapshots/useSnapshot.ts
- src/components/utilityFunctions.ts
- src/constants.ts
- src/server.ts
- src/types.ts
In order to do #1028 properly, we need to have a UI to edit the preferences. This PR just provides a couple of additional Admin endpoints (`get-all-prefs`, `set-prefs`) to facilitate this.
Front-end PR https://github.com/openmsupply/conforma-web-app/pull/1497
Documentation for all preferences included here too.
> #1028 (precursor) preferences endpoints

- src/components/exportAndImport/exportToJson.ts
- src/components/exportAndImport/getDatabaseInfo.ts
- src/components/exportAndImport/types.ts
Fixes #1019 
Took a while to figure out what was going on here -- bit of a rabbit hole to go down.
The problem was in the way the filter references are generated in `exportToJson.ts` -- because the "template" table has a reference to "templateCategory", a template filter would be generated restricting it to templateCategory ids already found when accessing templateCategory records. But there would be no templateCategory records, cos they had already been restricted by templateID (and in this case the templateCategoryId for the template is `null`) -- so it was a bit circular, and ended up putting a filter like this on template records:
```
{ templateCategoryId: { in: [] }, id: { equalTo: 98 } }
```
The template export query injects a bunch of filters into the `options` object already (from …
> #1019 Fix template export bug

- database/buildSchema/43_views_functions_triggers.sql
An additional fix for https://github.com/openmsupply/conforma-web-app/issues/1539
(Front-end PR: https://github.com/openmsupply/conforma-web-app/pull/1540)
This prevents more than one active version of the same trigger being added to the trigger queue. The front-end PR should solve the problem, but this is extra protection in case there are any other ways to cause duplicate triggers (such as setting triggers via direct API calls/Postman).
> #1539F Multiple trigger protection

- database/buildSchema/43_views_functions_triggers.sql
- database/migration/databaseMethods.ts
- database/migration/migrateData.ts
- package.json
- plugins/action_generate_review_assignment_records/src/generateReviewAssignments.test.ts
- plugins/action_generate_review_assignment_records/src/generateReviewAssignments.ts
- plugins/action_grant_permissions/src/grantPermissions.test.ts
- plugins/action_modify_record/src/modifyRecord.test.ts
- plugins/action_trim_responses/src/trimResponses.test.ts
- plugins/action_trim_responses/src/trimResponsesWithoutDatabase.test.ts
- plugins/action_update_review_visibility/src/updateReviewVisibility.test.ts
- src/components/actions/throttle.ts
- src/components/database/postgresConnect.ts
- src/components/database/updateReviewerStats.ts
- src/config.ts
- src/types.ts
Fix #1120 
- Remove the "Insert" trigger for `review_assignment` and `review_assignment_assigner_join`, as this was causing the update function to run way too many times[^1] whenever review assignments were generated. Instead it just gets run once and is called by the `generateReviewAssignments` Action.
- Move the "updateReviewerStats" function to a server function, triggered by database notification (and other things) rather than a PG function. Makes it much easier to see when it's running
- Made sure "updateReviewerStats" gets called async and send to the Throttle queue, which means it has to wait until the current action sequence is complete, and won't block the UI (as the Action triggers don't wait for it)
- Make `updateReviewerStats` callable by command line, so we can run manually …
> #1120 Improvements for Reviewer stats updates
