documentation/Action-plugin-specification.md, documentation/List-of-Action-plugins.md
First version of **action plugin** spec.
A few things to think about/discuss in **Needs consideration**
=> #21 Action plugins spec

documentation/Home.md, documentation/Question-Plugin-Bundles.md, documentation/Template-Builder.md
I just pushed the current docs to the wiki, then had a look over it.
Made a few changes here, mainly just re-organised the main Table of Contents.
@nmadruga -- feel free to make any adjustments of your own and push them directly to this branch/PR, then we can merge it (and push to wiki) when you're ready.
=> Table of Contents

database/buildSchema/16_application.sql, database/insertData.js, documentation/Database-Schema-Application.md
Required for Front-end PR of issue application-manager-web-app PR #31 -#33 (https://github.com/openmsupply/application-manager-web-app/pull/50)
=> #79 change application serial to string

database/buildSchema/09_template_section.sql, database/buildSchema/14_template_element.sql, database/insertData.js, src/generated/graphql.ts
Fixes #82.
We should hold off on merging this branch to `master` until #58 is done in front-end and then merge them both together.
=> Update schema to use index rather than nextElement

database/buildSchema/14_template_element.sql, database/insertData.js, documentation/Database-Schema-Template.md, src/generated/graphql.ts, src/plugins/action_increment_stage/src/incrementStage.ts
Implemented the things marked "TO-DO" in "Template element fields" in #61 (and updated Templates accordingly).
Will be useful for implementing Response local state in front-end (working on it now).
Have updated front-end docs with the specs, and added a link in these docs to that (not active yet, but will be once front-end issue is published).
=> Template element schema adjustments

database/insertData.js
Needed to go with front-end bug-fixes. (https://github.com/openmsupply/application-manager-web-app/pull/112)
Just changes the fields sent to `createUser` Action to `responses.Q1.text` rather than `responses.Q1`, so it handles correctly formatted Response object.
Reset database (`yarn database_init`) and restart server before testing.
=> Bug fix -- template definition tweak

package.json, src/components/permissions.ts, src/components/postgresConnect.ts, src/server.ts, yarn.lock
Fixes front end issue: https://github.com/openmsupply/application-manager-web-app/issues/64
Prerequisite For: https://github.com/openmsupply/application-manager-web-app/pull/123
Currently based to 84, should be rebased to master once 84 is merged
* Make sure CORS allows dev from different port (domain)
* Key template elements by code
=> F#64 use permission end point

database/insertData.js
Another addition required for [Front-end#81](https://github.com/openmsupply/application-manager-web-app/issue/81) issue. And [Front-end#127](https://github.com/openmsupply/application-manager-web-app/pull/127) PR.
Basically adds one element per section in the Company registration application to allow testing the Progress Bar properly.
=> #81F add elements to sections

database/insertData.js
Added three more organisation entries.
As far as I can tell, the primary requirement of this issue ("Create template action to change status of 'Create company' when submit application") is already done:
```
{
actionCode: "changeStatus"
trigger: ON_APPLICATION_SUBMIT
parameterQueries: {
applicationId: {
operator: "objectProperties"
children: [{ value: { property: "record_id" } }]
}
newStatus: { value: "Submitted" }
}
}
```
Was there any more to it?
=> #97 Add more companies

database/insertData.js
Back-end counterpart to front-end issue #126/PR132: https://github.com/openmsupply/application-manager-web-app/pull/132 
NOTE: Don't merge this until that issue is merged to `master`.
All this does is update the UserRego template to correctly use the new DropdownSelector plugin.
=> #126F Plugin generalisation & Dropdown plugin

database/insertData.js
Changes to the "Testing" template to showcase dynamic parameters in template elements.
Required for [front-end issue #124 PR](https://github.com/openmsupply/application-manager-web-app/pull/171)
=> #124F Template changes for dynamic fields

database/buildSchema/27_review.sql, src/generated/graphql.ts
note review appears in review_assignment
=> bug fix review to review_assignment reference

database/buildSchema/18_application_stage_history.sql, database/insertData.js, src/plugins/action_change_status/src/changeStatus.js, src/plugins/action_grant_permissions/src/grantPermissions.js, src/plugins/action_increment_stage/src/incrementStage.js
Fixes #151. 
Template element ids were incorrect. Must have occurred because of other changes. That's the trouble with hard-coding these links, but we don't really have a better way currently. 
Also:
- added `isActive: true` to this template.
- updated format and default time to application_stage_history `time_created` field (Missed last week).
- Rebuilt plugins (.js) since we noticed that (at least) one of them didn't match the lastest `.ts` source.
=> #151 Template fixes

database/buildSchema/26_review_assignment.sql, database/buildSchema/31_application_trigger_states.sql, src/components/postgresConnect.ts, src/generated/graphql.ts
Back-end changes for [front-end issue 202/PR 219](https://github.com/openmsupply/application-manager-web-app/pull/219).
Updates the application_trigger_states view to allow for review and review_assignment triggers as well.
=> #202F Trigger processing udpates

src/modules/expression-evaluator/src/evaluateExpression.test.ts, src/plugins/action_create_user/src/createUser.test.ts
I just noticed that the test suite had been neglected of late, and several of the tests were no longer passing due to changes in the database.
Quick fix here to update the expected results accordingly.
(After `yarn database_init` run `yarn test`)
=> Test suite fixes

database/insertData.js, src/components/databaseConnect.ts, src/components/permissions.ts, src/components/postgresConnect.ts, src/server.ts
Back-end companion to [front-end issue 145/PR 223](https://github.com/openmsupply/application-manager-web-app/pull/223)
**Changes**:
- Extend `/login` endpoint to also return "User" information as well as permission information
- new `getUserDataByUsername` database function
- Update Demo template to show access to `currentUser` object
=> #145F User state info

database/insertData.js, src/plugins/action_create_user/src/createUser.test.ts
Based on PR #152, please merge that one before this one.
=> #177F Adding 2nd reviewer and update password to be the same one

database/insertData.js, src/components/postgresConnect.ts
Branch to be used in pair with Front PR of [issue#216](https://github.com/openmsupply/application-manager-web-app/issues/216)
- Update dummy users password to be the same
- Include user `id` in the **getUserInfo** response
=> #216F Add user id to user fetch

database/buildSchema/07_template.sql, database/buildSchema/08_template_stage.sql, database/insertData.js, documentation/Database-Schema-Template.md, src/generated/graphql.ts
Branch to be used in pair with Front PR of [issue#138](https://github.com/openmsupply/application-manager-web-app/issues/138)
- Add `submissionMessage` to some template. The ones without a submission message will get the default one.
- Add `description` to stages on each existing template.
=> #138F submission page

database/buildSchema/03_user.sql, src/generated/graphql.ts
Fixes #169. Just adds UNIQUE constraint to username on user table.
=> #169 Unique username in Database

database/insertData.js, src/modules/expression-evaluator/expression-evaluate-gui/yarn.lock
Update to mock data so changes in [front-end #242](https://github.com/openmsupply/application-manager-web-app/pull/242) can be demonstrated.
~~**NOTE**: This still uses the old array format for the evaluator objects. It will need to be updated after #159 is merged (and again after #158), so hopefully they can be approved before this one and I'll merge them back into here and do those changes before this is merged.~~
(Done)
=> #232F Start message expression

database/buildSchema/27_review.sql, database/insertData/07_review_assignments.js, src/generated/graphql.ts
Implements #207. 2 additional auto-generated columns as per schema.
=> #207 Auto-generated columns on Review table -- level and is_last_level

database/buildSchema/29_review_response.sql, src/generated/graphql.ts
Fixes #231 
new field and trigger
"select * from review_response", you should see original_review_response is populated
=> #231 add trigger to associate original response

database/buildSchema/31_review_status_history.sql, src/generated/graphql.ts
Fixes [Front-end#428](https://github.com/openmsupply/application-manager-web-app/issues/428)
To be used in parallel with [Front-endPR#435](https://github.com/openmsupply/application-manager-web-app/pull/435)
=> Rename exposed field to timeStatusCreated

database/insertData/core_actions.js
=> #252-remove-updateReview-ON_REVIEW_SUBMIT

src/plugins/action_trim_responses/src/databaseMethods.ts, src/plugins/action_trim_responses/src/trimResponses.ts
=> #256-set-timestamp-in-trimResponses-from-db-records

database/buildSchema/06_trigger_queue.sql, database/insertData/core_actions.js, src/generated/graphql.ts
Required for this front end PR: https://github.com/openmsupply/application-manager-web-app/pull/446
* added new status to trigger, and added action to core actions to changes application to status when it's re-started
=> #314fe requires restart status

database/insertData/07_review_assignments.js
To be used for [Front-end PR#381](https://github.com/openmsupply/application-manager-web-app/pull/452)
- Fix one question assigned to INFORMATION element
- Fix for question assignment ids
- Commenting Review assignment so it's easier the mock data for current reviews in progress/submitted
- Added one Review (For reviewer 2, Application 34567) as **Locked**
=> #381F Updating Review assignments for ReviewTest applications

database/insertData/03_template_A_featureShowcase.js
Added a new section in Feature Showcase template with some variations of the new File Upload elements. This branch required for testing front-end File Upload plugin ([PR #454](https://github.com/openmsupply/application-manager-web-app/pull/454))
=> #432F File upload elements in template

database/buildSchema/06_trigger_queue.sql, database/insertData/core_actions.js, src/components/postgresConnect.ts, src/generated/graphql.ts, src/plugins/action_trim_responses/src/trimResponses.ts
Fixes: #269
* added re-start review status and action (change review to draft)
* fixed update of reviewResponses
=> #443f and #260 restart status for review, and fix update of reviewResponse in trimResponses

database/insertData/03_template_A_featureShowcase.js
Just adds one new element to Feature Showcase -- a Dropdown using GraphQL to show a list of companies. Required for [front-end issue #484](https://github.com/openmsupply/application-manager-web-app/issues/484) to demonstrate the GraphQL look-ups working.
=> #484F Graphql queries in form

database/insertData/02_permission_names.js, database/insertData/03_template_A_featureShowcase.js, database/insertData/03_template_B_companyRegistration.js, database/insertData/03_template_D_basicReviewTesting.js, database/insertData/03_template_E_drugRegistration.js, database/insertData/04_users.js, src/generated/graphql.ts
Fixes #270 
- Basically moving the Drug Registration template to be based on master
- Also adding users (as in demo-22-03) and permissions to do Apply, Assignment and Reviews
- Changed a little existing users to use the GeneralApply and GeneralAssign instead of specific ones to each template
- Any applicant user has access to apply to new template, but the reviewer/assignment isn't working on this branch - I have no idea why. Can continue to investigate as part of moving my next PR to be based on master.
=> #270 Drug Registration on master

database/insertData/03_template_C_userRegistration.js, database/insertData/core_actions.js
Fixes front end: https://github.com/openmsupply/application-manager-web-app/issues/609
As per comment: https://github.com/openmsupply/application-manager-web-app/issues/609#issuecomment-819158126
=> #609F-fix-application-start-bug

database/buildSchema/26_review_assignment.sql, src/generated/graphql.ts
Very small change -- complement of [front-end PR #607](https://github.com/openmsupply/application-manager-web-app/pull/607)
=> #573F Replace timeCreated with timeUpdated

database/insertData/03_template_C_userRegistration.js
Small tweak to complement changes done in [front-end PR #659](https://github.com/openmsupply/application-manager-web-app/pull/659)
=> #656F Update welcome message for UserRegistration

database/insertData/core_actions.js
Fixes: https://github.com/openmsupply/application-manager-web-app/issues/665
=> 665F Make sure review status is set before trigger is cleared

database/insertData/03_template_A_featureShowcase.js, database/insertData/03_template_B_orgRegistration.js, database/insertData/03_template_C_userRegistration.js, database/insertData/03_template_D_basicReviewTesting.js, database/insertData/03_template_E_drugRegistration.js, database/insertData/03_template_F_organisationJoin.js
Just adds a "style" parameter to TextInfo plugins, which is utilised in [front-end PR #680](https://github.com/openmsupply/application-manager-web-app/pull/680)
=> #600F TextInfo element -- style option

database/buildSchema/14_template_element.sql, database/insertData/03_template_A_featureShowcase.js, database/insertData/03_template_B_orgRegistration.js, database/insertData/03_template_C_userRegistration.js, database/insertData/03_template_E_drugRegistration.js, database/insertData/03_template_F_organisationJoin.js, src/generated/graphql.ts
Back-end changes required for front-end PR ???
- Schema change to include `help_text` field in `template_element`
- Updates to templates to make use of help text.
(Note: branch is misnamed -- has "#600..." in it, should be "#645..."
=> #645F Help tips text back-end

database/insertData/03_template_A_featureShowcase.js
Back-end branch for [front-end PR #732](https://github.com/openmsupply/application-manager-web-app/pull/732)
Just adds a **listBuilder** element (with sub-elements) to **FeatureShowcase** template (Section 3, Page2)
Couple of other tiny tweaks to template as well.
=> #489F Ingredients list demo

database/insertData/03_template_A_featureShowcase.js
Back-end for [front-end PR #748.](https://github.com/openmsupply/application-manager-web-app/pull/748) Only changed the checkbox in ListBuilder for now.
=> #731F Checkbox unselected text value

database/buildSchema/26_review_assignment.sql, database/buildSchema/31_review_decision.sql, database/insertData/06_applications_D_reviewTest.js, database/insertData/07_review_assignments.js, plugins/action_update_review_status/src/databaseMethods.ts, plugins/action_update_review_status/src/updateReviewsStatuses.test.ts, plugins/action_update_review_status/src/updateReviewsStatuses.ts, src/components/postgresConnect.ts, src/generated/graphql.ts
Just a tiny change that was on my TODO list
I haven't checked with all tests... But I think many still need to be updated after latest changed to the test data.
=> Update review_decision and tests using old enum types

database/insertData/03_template_A_featureShowcase.js
Adds "search" question elements to FeatureShowcase template, to demonstrate the Search element from [front-end PR 747](https://github.com/openmsupply/application-manager-web-app/pull/747)
=> #120F Search plugin (API lookup)

database/insertData/_common/02A_permission_names.js, database/insertData/_common/03_template_C_userRegistration.js, database/insertData/_common/04_outcome_displays.js, database/insertData/laos/01_users.js, database/insertData/laos/02_template_orgRegistration.js, database/insertData/laos/03_template_license_MMC_MMD.js
Added some changes to get ready for demo server:
* Tried to minimise and simplify permissions names and user set for lao data file
* Added further user outcomes
* Added further org outcomes
* Changed default values for object response to be an empty object
* Made populated fields editable (for licence)
* Fixed professional details in licence
=> #384-2 lao templates update

database/buildSchema/22_application_response.sql, database/buildSchema/30_review_response.sql
Should have really included this as part of #438 PR -- this does exactly the same thing, but for the review_response table. 
(Plus, fixed a couple of small naming issues in the last one 😳)
=> #430(2) Trigger/Function on review_response

database/insertData/_common/02A_permission_names.js, database/insertData/_common/04_outcome_displays.js, database/insertData/laos/02_template_orgRegistration.js, database/insertData/laos/03_template_license_MMC_MMD.js, database/insertData/laos/03_template_license_renewal_MMC_MMD.js, src/components/triggersAndActions.ts
Attempt to add template for "Renew Company License", the search for license isn't working though. Creating this PR now just so others can help with that, I've already spent to much time trying to understand what is wrong but no lucky.
I check that the objectProperty is building the "orgId" correctly as string - when using the EvaluationExpression UI, I don't know how I can check if `currentUser.organisation.orgId` it's coming correct though.
The problem that I'm facing is on the search element in the template "03_template_license_renewal_MMC_MMD` source field where the operator "graphQL" should be getting 2 inputs, but one of then is always failing:
Would be easier to test once Snapshot PR is in since to test this will require:
1) Create a company
2) Get approval to have access to …
=> #385 - New template company license renewal mmd mmc (and some help please)

database/insertData/dev/07_review_assignments.js
Back-end PR for Front-end https://github.com/openmsupply/application-manager-web-app/pull/862
Based on PR #456 
- Quick addition of reviewResponses so the current reviews work well with snapshot feature
- Fix reviews to have missing questionAssignments for application 34567
=> #859F fix app breaking with half consolidation misconfiguration

database/buildSchema/16_application.sql, database/buildSchema/19_application_status_history.sql, documentation/Database-Schema-Application.md, src/generated/graphql.ts
Fixes #472 
Make changes as described. I kept the "COMPLETED" status the same (as opposed to "DONE" or "CLOSED") as I thought that was more straightforward than changing all the existing templates, etc. that currently change outcome to "COMPLETED". Happy to change if we feel strongly.
=> #472 Outcome/Status value changes

database/insertData/dev/04_users.js
Fixes #489 
Just adds `applyUserEdit` to existing users.
=> #489 applyUserEdit permission to existing users

documentation/API.md
=> #465 documentation for run-action endpoint

docker/Dockerfile
Needs front end branch in this PR:https://github.com/openmsupply/application-manager-web-app/pull/898
I've added this to demo-08-08-2021 branch (current demo server branch).
Commit should  pretty straight forward.
=> add version to build

docker/Dockerfile, docker/run.sh, src/components/exportAndImport/importFromJson.ts
Sorry no issue:
* add libre office to docker build
* show how environmental variables can be passed to server when docker image is being run
* make sure that missing values are not imported as undefined when loading snapshot
=> Demo build changes

src/modules/expression-evaluator/package.json, src/modules/expression-evaluator/src/evaluateExpression.test.ts, src/modules/expression-evaluator/src/evaluateExpression.ts, src/modules/expression-evaluator/src/evaluateExpressionTestData.ts, src/modules/expression-evaluator/src/resolvers/buildObject.test.ts
Fixes #485 (indirectly) -- see [this comment](https://github.com/openmsupply/application-manager-server/issues/485#issuecomment-890276358)
A general solution for adding arbitrary functions to evaluator, so we can add any additional functionality we require without adding loads of operators.
This PR just has the evaluation and a couple of tests to demonstrate it, but I've used this to generate expiry dates for products/outcomes in the Scheduled Actions (PR coming soon), and it works nicely for that.
- Also updated existing test due to changing database data
=> #485 objectFunctions for evaluator

README.md, src/components/actions/getApplicationData.ts
Fixes #432
You'll need to also add this line to your `.env` file:
```
WEB_HOST = "http://localhost:3000"
```
I still need to update the templates to use this, but I'll do that on the demo server snapshot
=> #432 Add webhost URL to applicationData

documentation/API.md, documentation/List-of-Action-plugins.md
Somehow these slipped through, so just updating docs for these 2 actions.
=> Missing docs for actions (generateDoc and sendNotification)

database/buildSchema/04_organisation.sql, database/buildSchema/05_user_organisation.sql, src/components/permissions/loginHelpers.ts, src/components/postgresConnect.ts, src/generated/graphql.ts, src/types.ts
Back-end for [front-end PR #914](https://github.com/openmsupply/application-manager-web-app/pull/914)
See that PR and issue for more info
=> #911B Specify "system" org (i.e. FDA) with additional flag field

database/buildSchema/16_application.sql
Fixes: #522 
update for trigger vs insert, merged to demo already.
@CarlosNZ, I think we need to also do a condition of OLD.outcome = 'PENDING" ?
=> 522-snapshot-to-work-when-importing-completed-application

docker/demo_server/docker-compose.yml, documentation/Demo-Server-Guide.md
Reshuffles order of topis in guide, adding a few tips.
Update documentation and fix docker-comppose.yml file:
- To be using environment variable to SMTP_PASSOWRD
- Get docker repo:tag also needs account-name passed to be used in the server
=> Updates to Demo-Server guide

docker/demo_server/docker-compose.yml, documentation/Demo-Server-Guide.md
=> Demo server yml config and guide update

src/components/exportAndImport/getDatabaseInfo.ts, src/components/exportAndImport/importFromJson.ts, src/components/exportAndImport/types.ts, src/components/snapshots/useSnapshot.ts
Fixes: #557 
Hopefully commit title and content should explain the changes
=> #557 fix snapshot import with product outcomes

database/basic_snapshot/snapshot.json
Just changes to basic_snapshot with fix to changeOutcome core-action
=> #865F Adding send notifications to applicant in basic_snapshot for APPROVE/REJECT and LOQ 

database/basic_snapshot/snapshot.json, database/buildSchema/22_application_stage_status.sql, src/components/permissions/routes.ts, src/components/postgresConnect.ts, src/generated/graphql.ts, src/types.ts
Back-end changes required for sessionId handling in the front-end (Front-end PR [#975]( https://github.com/openmsupply/application-manager-web-app/pull/975))
- made sure `sessionId` field was passed through if present in "login" and "userInfo" endpoints, and the return object contains the same sessionId if present (or a random one if not, as before)
- added "sessionId" to "applicationData" (for back-end) so can be accessed in Actions
=> #966F sessionId handling

database/buildSchema/02_user.sql
=> #583 fix date of birth field

src/components/snapshots/routes/index.ts, src/components/snapshots/routes/routeDeleteSnapshot.ts, src/generated/graphql.ts
So we can delete snapshots in the UI.
Required for [front-end #998](https://github.com/openmsupply/application-manager-web-app/pull/998)
=> #993F Delete snapshot endpoint

docker/dockerise.sh, plugins/action_generate_document/plugin.json, plugins/action_generate_document/src/generateDoc.ts, src/components/files/documentGenerate.ts, src/generated/graphql.ts
Missing change done on the old Portuguese-localisation PR...
Used to get a generated certificate using Carbone localisation (use to translate dates and currency)
=> #update action generate doc to use localised options

documentation/Demo-Server-Guide.md
Problem was that when the exiting instance was running the commands to stop it were not clear and took me some time to find out.
=> Add updates to Demo-Server-Guide for launching instance with new datafile

.postgraphilerc.js, docker/demo_server/docker-compose.yml, docker/run.sh, documentation/Demo-Server-Guide.md, src/config.ts, utils/build_all.sh
This will need to be tested properly. I can confirm that the build process should work fine and the docker image runs locally okay. There's still some weirdness with files not showing up correctly and some other things which I'll look into and maybe push to this PR too.
**Update**: When running the docker image locally, the core_templates snapshot hasn't fully loaded properly, although it's there enough to log in. So I can manually import a snapshot (including core_templates) and load that which works. But now I get this error when trying to start a new "User Registration"
Inspecting the network logs, it's failing when trying to access `http://localhost:3000/postgraphile/graphql/api?dev=getTemplates` This doesn't seem right, but not sure why it's requesting that.
=> Additional build fixes

documentation/API.md, src/components/databaseConnect.ts, src/components/permissions/routes.ts, src/components/permissions/types.ts, src/components/postgresConnect.ts, src/types.ts
Needed to list permissions for company before adding an user - CreateInternalUser template (version 2)
=> #allow user permissions to list org permissions

database/buildSchema/28_review_assignment.sql, src/generated/graphql.ts
[Front-end PR](https://github.com/openmsupply/application-manager-web-app/pull/1124) in progress
=> Fix setting assignedSections to null when status is AVAILABLE

src/components/actions/evaluatorFunctions.ts, yarn.lock
Used for U2-OrgRegistration emails
=> Add new functions to get current date on server

README.md, database/buildSchema/15_template_permission.sql, database/migration/migrateData.ts
Closes #742 
No changes to the actual endpoint code, it's all about just making sure the "permissions_all" View includes permission_names that don't have associated templates (via a LEFT JOIN)
Also fixed some erroneous migration code that had slipped through untested.
=> #742 Update user permissions endpoint

database/reset_serial.sql, package.json
closes: #800 
Description as per comments
=> 800-Update-serial-reset-sql

src/components/actions/evaluatorFunctions.ts
@nmadruga -- can you please check this works?
Once you're happy with it, please merge it, but then also copy and paste the whole contents of `evaluatorFunctions.ts` into the front-end equivalent and merge it straight to develop.
Thanks.
=> Formatted date fix

database/buildSchema/06_template_category.sql, database/migration/migrateData.ts, src/components/permissions/loginHelpers.ts
Back-end changes required for front end-issue https://github.com/openmsupply/conforma-web-app/issues/1270
Front-end PR: https://github.com/openmsupply/conforma-web-app/pull/1283
- Adds a new UI location -- "MANAGEMENT" -- appears as new Menu bar item
- Schema migration to add the above
- user-info/login endpoints also return an array of permission names (needed to determine if user has "management" permissions, but will probably come in handy elsewhere)
=> 1270F Admin differentiation

database/core_templates/snapshot.json
Nothing really here -- just added "displayFormat: checkboxes" to a couple of the Checkbox elements in Feature Showcase, for the purposes of demonstrating front-end https://github.com/openmsupply/conforma-web-app/issues/1298 changes
=> #1298F Checkbox tweak in Core templates

database/buildSchema/32_review_response.sql, database/migration/migrateData.ts
Just add an extra clause to the WHEN condition.
Use latest Angola snapshot angola_2022_09_02_1530
We should make sure we start a new review and submit it before we approve this.
=> #820 (Part 2) -- fix dodgy trigger

plugins/action_modify_record/src/modifyRecord.test.ts, plugins/action_modify_record/src/modifyRecord.ts
Fix #832 
Simple fix -- see issue for explanation of the problem.
Also updated tests
=> #832 modifyRecord null fix

database/buildSchema/45_activity_log.sql, database/migration/migrateData.ts, plugins/action_change_status/src/changeStatus.ts
Front-end PR: https://github.com/openmsupply/conforma-web-app/pull/1338
Please see description of PR in Front-end
=> #1214F warning on reviewer is unassigned

database/buildSchema/39_assigner_action_list.sql, database/migration/migrateData.ts
Previous problem was this:
It would show this for the Assigner (or Review with self-assignment rights) regardless of application being Expired (Caduco) or not:
=> #1339F - Quick fix to not show action to Assign on list for Assigner

src/components/graphQLConnect.ts, src/types.ts
=> Adding reviewer details on reviewData object accessible in actions

src/components/localisation/routes.ts
Changes to be used in Reviewing [Back-end PR](https://github.com/openmsupply/conforma-web-app/pull/1355)
=> Small change on languages fields

database/buildSchema/04_user_organisation.sql, database/migration/migrateData.ts, documentation/List-of-Action-plugins.md, plugins/action_join_user_org/src/joinUserOrg.ts, plugins/action_remove_user_org/package.json, plugins/action_remove_user_org/plugin.json, plugins/action_remove_user_org/src/index.ts, plugins/action_remove_user_org/src/removeUserOrg.ts, src/components/databaseConnect.ts, src/components/postgresConnect.ts
Fix #870 
Very simple -- just deletes the `user_organisation` record
=> #870 Action to remove user from org

docker/demo_server/nginx_config/default, docker/demo_server/nginx_config_single/default
Fixes https://github.com/openmsupply/conforma-templates/issues/38
Follow an advise to use this error_page 497 (for HTTP requests) to be redirected to the proper ssl url
=> #38T Update NGINX Config to redirect traffic on HTTP requests

documentation/Backups.md, documentation/Demo-Server-Guide.md, src/components/exportAndImport/backup.ts
The Dropbox coniguration is not strictly part of Conforma, but it took me a while to work it out, so figured it's probably useful to have as a reference. We can add other cloud services if/when we use them.
=> Documentation for Backups / Dropbox

documentation/Demo-Server-Guide.md
- Tip on how to copy log from server into a local file for analysis
=> Documentation - addition to copy log into local

database/buildSchema/16_template_element.sql, database/migration/migrateData.ts, src/generated/graphql.ts
Closes #1010 
Not much required for back-end, just a little migration.
=> 1010 rename default value column

documentation/Demo-Server-Guide.md
=> Add cloudVPS documentation

src/components/data_display/helpers.ts, src/components/data_display/routes.ts, src/components/data_display/types.ts
As per title, required for https://github.com/openmsupply/conforma-web-app/pull/1489
=> 1486F Return defaultFilterString in DataViewTable response

src/components/actions/coreActions.ts
Fix #1030 
Fixed as per comment in code.
=> #1030 Fix core action mutation bug

database/migration/migrateData.ts, src/components/data_display/routes.ts, src/components/data_display/types.ts, src/components/utilityFunctions.ts
~~Implement sub-menus for Data Views. Started with Data Views as its the simplest. Once we're happy with the general way its working I'll include for other menus too.~~
Just makes small changes to schema to include submenu info.
Test with front-end https://github.com/openmsupply/conforma-web-app/pull/1515
=> #1044 Schema changes for submenus

database/migration/migrateData.ts
Fix #1045 .
Just adds an extra column to "template" for Dashboard restrictions. Most of the functionality is in front-end
Front-end PR: https://github.com/openmsupply/conforma-web-app/pull/1524
=> 1045 Dashboard restrictions

src/lookup-table/models/LookupTable.model.ts, src/lookup-table/services/LookupTable.service.ts, src/lookup-table/utils/validations/LookupTableHeaders.validator.ts
Fix #1086
As per bullet points in [issue](#1086)
=> #1086 lookup table improvements

database/migration/migrateData.ts, documentation/API.md, documentation/List-of-Action-plugins.md, plugins/action_generate_text_string/src/generateTextString.ts, plugins/action_modify_record/src/databaseMethods.ts, plugins/action_modify_record/src/modifyRecord.ts, src/components/actions/coreActions.ts, src/components/data_display/helpers.ts, src/components/data_display/postGresToJSDataTypes.ts, src/components/databaseConnect.ts, src/components/other/routeRawData.ts, src/components/postgresConnect.ts, src/components/utilityFunctions.ts, src/config.ts, src/server.ts, src/types.ts
Add a "data_changelog" table, and update "modifyRecord" action to write change details to it, so we have a log of any data changed in the system.
- Also add a "delete" option to "modifyRecord"
- Return "enum" data type in Data view definitions
- `/raw-data` endpoint to get unmodified database data for data table records (Admin only)
=> Data changelog

database/migration/migrateData.ts, src/generated/graphql.ts
Fix [#1545](https://github.com/msupply-foundation/conforma-web-app/issues/1545)
=> 1545F Template dashboard priority

database/migration/migrateData.ts, documentation/List-of-Action-plugins.md, plugins/action_modify_record/src/databaseMethods.ts, plugins/action_modify_record/src/modifyRecord.ts, src/components/postgresConnect.ts
Fix https://github.com/msupply-foundation/conforma-templates/issues/269
=> 269T Comment for data_changelog
